"""Dataclasses shared across frf_separate.

Mirrors the small "data carrier" structs in Phaser
(phenix-1.20-4459/modules/phaser/codebase/phaser/src/SiteListAng.h,
 src/DataMR.h) without trying to keep the same names everywhere —
crystallographic intent first, C++ naming second.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import List, Tuple

import torch


@dataclass
class BesselSHCoefficients:
    """Bessel-radial × spherical-harmonic coefficients ``c_{n, l, m}``.

    Phaser source: DataMR.cc constructs the equivalent ``c_lmn`` 3D complex
    grid inside ``DataMR::dataMR_FRF`` (not shown here — see annotations).

    Shape: ``coeffs[n, l, m + L - 1]`` is complex, with l ∈ [0, L) even-only,
    n ∈ [0, N_radial), m ∈ [-l, l] (zero-padded outside).
    """

    coeffs: torch.Tensor          # (N_radial, L, 2L-1), complex
    L: int                         # angular bandlimit (lmax = L - 1)
    N_radial: int                  # number of radial nodes
    bessel_h_scale: float          # h = bessel_h_scale * |s|


@dataclass
class WignerContraction:
    """The per-β ``S_{m1,m2}(β) = Σ_l ξ_{l,m1,m2} · d^l_{m1,m2}(β)``.

    Phaser source: ``SiteListAng::DoRfftStuff`` (FastRot.cc:39-59) builds
    this sum into the ``rot`` accumulator before pushing into a pseudo-SF
    array for FFT.
    """

    S: torch.Tensor                # (n_beta, 2L-1, 2L-1), complex
    betas: torch.Tensor            # (n_beta,), real


@dataclass
class AdaptiveRotationFunction:
    """Rotation function values on Phaser's adaptive SO(3) sample list.

    The samples live on a *non-rectangular* point set per β — generated by
    the ``allocate_memory`` routine in ``SiteListAng::allocate_memory``
    (FastRot.cc:169-262). Each β has a different number of samples; we
    store them concatenated, with ``beta_starts`` indexing into the flat
    arrays.

    The dense FFT map ``M_β(α, γ)`` (fixed shape across β) is *not* stored
    here — only the interpolated samples on the adaptive list.
    """

    alphas: torch.Tensor           # (N_samples,) real in [0, 2π)
    betas: torch.Tensor            # (N_samples,) real in [0, π]
    gammas: torch.Tensor           # (N_samples,) real in [0, 2π)
    values: torch.Tensor           # (N_samples,) real — RF values
    beta_starts: torch.Tensor      # (n_beta + 1,) int — slice indices per β
    beta_grid: torch.Tensor        # (n_beta,) real — the β values themselves
    grid_sampling_deg: float

    def total_samples(self) -> int:
        return int(self.values.numel())


@dataclass
class RotationPeak:
    """A single rotation function peak.

    Single source of truth across the FRF, the rescore, and the tests.
    Convention: Edmonds ZYZ Euler in radians.
    """

    alpha: float
    beta: float
    gamma: float
    score: float
    sigma: float
