"""
Pure-PyTorch Patterson-based rotation search.

Replaces the old `ball_transform.py` (which depended on jax / s2fft / s2ball /
spherical / quaternionic). All math is implemented with `torchref.alignment.sh`
and `torchref.alignment.wigner` and runs on whatever device the inputs live on.

Conventions (locked, asserted by tests/unit/alignment/test_*.py and the
synthetic-rotation integration test):

  Forward analytical SH expansion:
        f_{p,l,m} = Σ_{i ∈ shell p} v_i · conj(Y_{l,m}(ŝ_i))
  with Friedel mates `(-s_i, v_i)` included so odd-l rows are zero by
  construction.

  Cross-correlation in Wigner-D basis:
        ξ_{l,m,n} = Σ_p w_p · f_{obs}[p,l,n] · conj(f_{calc}[p,l,m])
        C(R)      = Σ_{l,m,n} ξ_{l,m,n} · D^l_{m,n}(R)         (Edmonds D)

  Recovered rotation: the Euler triple (α, β, γ) at the maximum of C is the
  rotation R = R_z(α) R_y(β) R_z(γ) (Edmonds active ZYZ) such that
        s_calc = R · s_obs                                    (column vector)
  for the test scenario where F_calc was generated by applying R to the model
  coordinates. To build a (3, 3) matrix using
  `torchref.alignment.transform.rotation_matrix_from_euler` (which interprets
  its args as `R = R_z(γ_arg) R_y(β_arg) R_z(α_arg)`), pass `[γ, β, α]`.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import List, Optional, Tuple

import torch
import torch.nn.functional as F

from .sh import (
    assign_shells,
    compute_patterson_shell_variance,
    equal_count_shell_edges,
    sh_expand_ball,
)
from .wigner import (
    evaluate_rotation_function_grid,
    evaluate_rotation_function_pointwise,
)


# =============================================================================
# Data containers
# =============================================================================


@dataclass
class BallHarmonicCoefficients:
    """Output of `compute_ball_harmonic_coefficients`."""

    f_plm: torch.Tensor  # complex, shape (P, L, 2L-1)
    L: int
    P: int
    shell_edges: torch.Tensor  # real, shape (P+1,)
    shell_centers: torch.Tensor  # real, shape (P,)
    shell_counts: torch.Tensor  # int64, shape (P,)


@dataclass
class RotationPeak:
    """A single peak of the rotation function."""

    alpha: float
    beta: float
    gamma: float
    score: float       # value of C at the peak (real part)
    sigma: float       # (C - mean) / std at the peak


# =============================================================================
# Forward expansion
# =============================================================================


def compute_ball_harmonic_coefficients(
    s_vectors: torch.Tensor,
    values: torch.Tensor,
    L: int = 48,
    P: int = 24,
    shell_edges: Optional[torch.Tensor] = None,
    d_min: Optional[float] = None,
    d_max: Optional[float] = None,
    enforce_friedel: bool = True,
) -> BallHarmonicCoefficients:
    """
    Compute the ball-harmonic expansion of a real scattered-point field.

    Parameters
    ----------
    s_vectors : (N, 3) real tensor
        Reciprocal-lattice vectors in 1/Å.
    values : (N,) real tensor
        Sample values (e.g. |E(h)|) at each `s_vector`.
    L : int, default 48
        Angular bandlimit.
    P : int, default 24
        Number of radial shells.
    shell_edges : (P+1,) real tensor, optional
        Pre-computed shell boundaries (in |s|). If None, use equal-count
        binning between `d_min` and `d_max` (or full range).
    d_min, d_max : float, optional
        Resolution bounds (Å). When given, reflections outside [1/d_max, 1/d_min]
        in |s| are discarded.
    enforce_friedel : bool, default True
        Augment input with (-s, value) pairs and zero odd-l rows after expansion.

    Returns
    -------
    BallHarmonicCoefficients
    """
    s_mag = s_vectors.norm(dim=-1)
    if d_min is not None or d_max is not None:
        s_lo = 1.0 / d_max if d_max is not None else 0.0
        s_hi = 1.0 / d_min if d_min is not None else float("inf")
        keep = (s_mag >= s_lo) & (s_mag <= s_hi)
        s_vectors = s_vectors[keep]
        values = values[keep]
        s_mag = s_mag[keep]

    if shell_edges is None:
        shell_edges, _ = equal_count_shell_edges(s_mag, P)
    shell_centers = 0.5 * (shell_edges[:-1] + shell_edges[1:])
    shell_idx = assign_shells(s_mag, shell_edges)
    keep = shell_idx >= 0
    s_vectors = s_vectors[keep]
    values = values[keep]
    shell_idx = shell_idx[keep]

    shell_counts = torch.bincount(shell_idx, minlength=P).to(torch.int64)

    f_plm = sh_expand_ball(
        s_vectors, values, shell_idx, P, L,
        enforce_friedel=enforce_friedel,
    )

    return BallHarmonicCoefficients(
        f_plm=f_plm, L=L, P=P,
        shell_edges=shell_edges,
        shell_centers=shell_centers,
        shell_counts=shell_counts,
    )


# =============================================================================
# Cross-correlation
# =============================================================================


def compute_ball_cross_correlation_coefficients(
    f_obs: BallHarmonicCoefficients,
    f_calc: BallHarmonicCoefficients,
    weights: Optional[torch.Tensor] = None,
) -> torch.Tensor:
    """
    Wigner-D coefficients ξ_{l,m,n} of the rotation function (see module docstring).

    ξ_{l,m,n} = Σ_p w_p · f_{obs}[p, l, n] · conj(f_{calc}[p, l, m])
    """
    assert f_obs.L == f_calc.L, "bandwidths must match"
    assert f_obs.P == f_calc.P, "shell counts must match"
    P, L = f_obs.P, f_obs.L

    if weights is None:
        # Default: weight by shell count (equal weight per reflection).
        counts = f_obs.shell_counts.to(torch.float64)
        w_sum = counts.sum().clamp(min=1.0)
        weights = (counts / w_sum).to(f_obs.f_plm.dtype)
    else:
        weights = weights.to(f_obs.f_plm.dtype)

    xi = torch.einsum(
        "p,pln,plm->lmn",
        weights,
        f_obs.f_plm,
        torch.conj(f_calc.f_plm),
    )
    return xi


# =============================================================================
# Peak finding
# =============================================================================


def _circular_pad_gamma_alpha(x: torch.Tensor, r: int) -> torch.Tensor:
    """
    Wrap-pad axes 0 (γ) and -1 (α) by `r` voxels using circular boundary
    conditions, and constant-pad axis 1 (β) with -inf (non-periodic).
    Input shape (Γ, B, Α); output shape (Γ+2r, B+2r, Α+2r).
    """
    if r <= 0:
        return x
    x = torch.cat([x[-r:], x, x[:r]], dim=0)                    # wrap γ
    x = torch.cat([x[..., -r:], x, x[..., :r]], dim=-1)         # wrap α
    pad_shape = list(x.shape)
    pad_shape[1] = r
    neg_inf = torch.full(pad_shape, float("-inf"), dtype=x.dtype, device=x.device)
    x = torch.cat([neg_inf, x, neg_inf], dim=1)                 # β: -inf pad
    return x


def find_rotation_peaks(
    C: torch.Tensor,
    alphas: torch.Tensor,
    betas: torch.Tensor,
    gammas: torch.Tensor,
    n_peaks: int = 200,
    sigma_threshold: float = 0.0,
    cluster_radius_voxels: int = 2,
) -> List[RotationPeak]:
    """
    Extract local maxima of `C` and return them sorted by descending value.

    Periodic in α and γ (FFT axes); β is non-periodic but mirror at the
    endpoints isn't enforced — the user is expected to oversample β.

    Patterson centrosymmetry C(R) = C(-R) is left to the caller — when needed,
    add a post-processing step that merges peaks with R and -R representations.

    Vectorised over voxels: NMS is implemented as `C == max_pool3d(C)` with
    `kernel = 2·r + 1`, circular in α and γ. The legacy per-voxel Python loop
    with per-iteration `.item()` is replaced with a single sort + bulk
    `.tolist()` at the end — same semantics on randomly-real data (exact
    ties are vanishingly rare), but device-portable and ~1-2 orders of
    magnitude faster.
    """
    C_real = C.real
    n_gamma, n_beta, n_alpha = C_real.shape
    flat_stats = C_real.flatten()

    mean = flat_stats.mean()
    std = flat_stats.std().clamp(min=1e-30)
    threshold = mean + sigma_threshold * std

    r = int(cluster_radius_voxels)
    if r > 0:
        padded = _circular_pad_gamma_alpha(C_real, r)
        # max_pool3d wants (N, C, D, H, W). Add batch+channel dims, then strip.
        pooled = F.max_pool3d(
            padded.unsqueeze(0).unsqueeze(0),
            kernel_size=2 * r + 1, stride=1, padding=0,
        )[0, 0]
        is_local_max = C_real >= pooled
    else:
        is_local_max = torch.ones_like(C_real, dtype=torch.bool)

    above_threshold = C_real >= threshold
    candidate = is_local_max & above_threshold
    candidate_flat = candidate.flatten()
    cand_idx = candidate_flat.nonzero(as_tuple=False).flatten()
    if cand_idx.numel() == 0:
        return []
    cand_vals = C_real.flatten().index_select(0, cand_idx)

    # Sort descending; truncate to n_peaks.
    top_k = min(int(n_peaks), int(cand_vals.numel()))
    sort_vals, sort_perm = torch.sort(cand_vals, descending=True)
    sel_flat_idx = cand_idx.index_select(0, sort_perm[:top_k])
    sel_vals = sort_vals[:top_k]

    # Convert flat → (g, b, a). Periodic axes have already been deduped, so
    # plain integer arithmetic is sufficient.
    nba = n_beta * n_alpha
    ig = sel_flat_idx // nba
    rem = sel_flat_idx - ig * nba
    ib = rem // n_alpha
    ia = rem - ib * n_alpha

    sigmas = (sel_vals - mean) / std

    # Bulk transfer to Python lists, then build dataclasses.
    a_list = alphas.index_select(0, ia).tolist()
    b_list = betas.index_select(0, ib).tolist()
    g_list = gammas.index_select(0, ig).tolist()
    v_list = sel_vals.tolist()
    s_list = sigmas.tolist()
    return [
        RotationPeak(alpha=a, beta=b, gamma=g, score=v, sigma=s)
        for a, b, g, v, s in zip(a_list, b_list, g_list, v_list, s_list)
    ]


# =============================================================================
# Sub-voxel refinement (pointwise gradient ascent on C(R) using autograd)
# =============================================================================


def _parabolic_offset_vec(
    y_minus: torch.Tensor, y_zero: torch.Tensor, y_plus: torch.Tensor,
) -> torch.Tensor:
    """
    Vectorised sub-voxel offset for a quadratic through three samples
    y(-1), y(0), y(+1). Returns δ clamped to [-1, 1]; degenerate cells
    (|denom| < 1e-30) get δ = 0.
    """
    denom = y_minus - 2.0 * y_zero + y_plus
    bad = denom.abs() < 1e-30
    safe_denom = torch.where(bad, torch.ones_like(denom), denom)
    delta = 0.5 * (y_minus - y_plus) / safe_denom
    delta = torch.where(bad, torch.zeros_like(delta), delta)
    return delta.clamp(-1.0, 1.0)


def refine_peaks_subvoxel(
    peaks: List[RotationPeak],
    C: torch.Tensor,
    alphas: torch.Tensor,
    betas: torch.Tensor,
    gammas: torch.Tensor,
) -> List[RotationPeak]:
    """
    Sub-voxel refinement of integer-grid peaks by separable quadratic fitting.

    For each peak, fits y = a + b·δ + c·δ² through the values at ±1 voxel along
    each of α, β, γ axes (α and γ periodic with the grid length, β not).
    Returns refined peaks with interpolated angles and values.

    Vectorised over all peaks: indices and neighbour samples are gathered in
    a single batched op; the legacy per-peak `.item()` loop is replaced with
    one `.tolist()` at the end (cuts ~12·K scalar GPU↔CPU round-trips).
    """
    if not peaks:
        return list(peaks)

    n_gamma, n_beta, n_alpha = C.shape
    Cr = C.real
    device = Cr.device
    real_dtype = alphas.dtype

    dalpha = (alphas[1] - alphas[0]).item()
    dgamma = (gammas[1] - gammas[0]).item()
    dbeta = (betas[1] - betas[0]).item() if betas.numel() > 1 else 0.0
    a0 = alphas[0].item()
    g0 = gammas[0].item()
    b0 = betas[0].item()

    # Pack peak coordinates into tensors in one go.
    K = len(peaks)
    alpha_in = torch.tensor([p.alpha for p in peaks], dtype=real_dtype, device=device)
    beta_in = torch.tensor([p.beta for p in peaks], dtype=real_dtype, device=device)
    gamma_in = torch.tensor([p.gamma for p in peaks], dtype=real_dtype, device=device)

    # Integer voxel indices.
    ia = ((alpha_in - a0) / dalpha).round().long() % n_alpha
    ig = ((gamma_in - g0) / dgamma).round().long() % n_gamma
    if dbeta > 0:
        ib = ((beta_in - b0) / dbeta).round().long().clamp(0, n_beta - 1)
    else:
        ib = torch.zeros(K, dtype=torch.long, device=device)

    am = (ia - 1) % n_alpha
    ap = (ia + 1) % n_alpha
    gm = (ig - 1) % n_gamma
    gp = (ig + 1) % n_gamma
    # β neighbours: clamp at boundaries; we zero δβ explicitly there below.
    ibm = (ib - 1).clamp(min=0, max=n_beta - 1)
    ibp = (ib + 1).clamp(min=0, max=n_beta - 1)

    y0 = Cr[ig, ib, ia]
    ya_m = Cr[ig, ib, am]
    ya_p = Cr[ig, ib, ap]
    yg_m = Cr[gm, ib, ia]
    yg_p = Cr[gp, ib, ia]
    yb_m = Cr[ig, ibm, ia]
    yb_p = Cr[ig, ibp, ia]

    da = _parabolic_offset_vec(ya_m, y0, ya_p)
    dg = _parabolic_offset_vec(yg_m, y0, yg_p)
    db = _parabolic_offset_vec(yb_m, y0, yb_p)
    # Zero out β offset at the boundary (single-sided / undefined).
    at_b_boundary = (ib == 0) | (ib == n_beta - 1)
    db = torch.where(at_b_boundary, torch.zeros_like(db), db)
    if dbeta <= 0:
        db = torch.zeros_like(db)

    two_pi = 2.0 * math.pi
    alpha_new = (alphas.index_select(0, ia) + da * dalpha) % two_pi
    gamma_new = (gammas.index_select(0, ig) + dg * dgamma) % two_pi
    beta_new = (betas.index_select(0, ib) + db * dbeta).clamp(min=0.0, max=math.pi)

    a_list = alpha_new.tolist()
    b_list = beta_new.tolist()
    g_list = gamma_new.tolist()
    return [
        RotationPeak(
            alpha=a, beta=b, gamma=g, score=p.score, sigma=p.sigma,
        )
        for a, b, g, p in zip(a_list, b_list, g_list, peaks)
    ]


# =============================================================================
# Top-level entry
# =============================================================================


def ball_rotation_search(
    s_obs: torch.Tensor,
    e_obs: torch.Tensor,
    s_calc: torch.Tensor,
    e_calc: torch.Tensor,
    L: int = 48,
    P: int = 24,
    n_peaks: int = 200,
    d_min: Optional[float] = None,
    d_max: Optional[float] = None,
    refine_subvoxel: bool = True,
    n_refine: int = 20,
    sigma_threshold: float = 1.0,
    weights: Optional[torch.Tensor] = None,
    auto_variance_weights: bool = True,
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, List[RotationPeak]]:
    """
    End-to-end Patterson rotation search.

    Parameters
    ----------
    s_obs, s_calc : (N, 3) real
        Reciprocal-lattice vectors. Need not be the same set of HKLs for obs
        and calc — but should sample the same resolution range.
    e_obs, e_calc : (N,) real
        Normalized structure-factor amplitudes (E-values). Pass |F|² instead
        if you want a strict Patterson rotation function.
    L, P : int, default 48 / 24
        Bandlimit and shell count.
    d_min, d_max : float
        Resolution limits in Å (s_min = 1/d_max, s_max = 1/d_min).
    n_peaks : int, default 200
        Number of rotation peaks to return.
    refine_subvoxel : bool, default True
        If True, refine the top `n_refine` peaks by gradient ascent on the
        pointwise rotation function (autograd, no FFT).
    n_refine : int
        Number of peaks to refine.
    sigma_threshold : float
        Minimum (peak - mean)/std for a peak to be kept.
    weights : (P,) real, optional
        Per-shell weights in the cross-correlation. Default: shell-count weighted,
        or (when `auto_variance_weights=True`) inverse-sqrt of the empirical
        per-shell variance of the obs Patterson coefficient.
    auto_variance_weights : bool, default True
        Compute `weights = 1/√Var(e_obs)_p` per shell when no explicit `weights`
        are supplied. This is the LERF1-style empirical variance correction —
        downweights shells whose observed Patterson coefficient is dominated by
        intermolecular contributions (high-symmetry crystals).

    Returns
    -------
    C : complex tensor (n_gamma, n_beta, n_alpha)
        Rotation function on Euler grid (Edmonds order).
    alphas, betas, gammas : real 1-D tensors
        Grid coordinates.
    peaks : list of RotationPeak (sorted by descending score)
    """
    f_obs = compute_ball_harmonic_coefficients(
        s_obs, e_obs, L=L, P=P, d_min=d_min, d_max=d_max,
    )
    # Share shell edges between obs and calc — required for the cross-correlation
    # to be meaningful (same radial binning on both sides).
    f_calc = compute_ball_harmonic_coefficients(
        s_calc, e_calc, L=L, P=P, shell_edges=f_obs.shell_edges,
    )

    if auto_variance_weights and weights is None:
        s_mag_obs = s_obs.norm(dim=-1)
        if d_min is not None or d_max is not None:
            s_lo = 1.0 / d_max if d_max is not None else 0.0
            s_hi = 1.0 / d_min if d_min is not None else float("inf")
            keep_obs = (s_mag_obs >= s_lo) & (s_mag_obs <= s_hi)
            s_mag_v = s_mag_obs[keep_obs]
            e_obs_v = e_obs[keep_obs]
        else:
            s_mag_v = s_mag_obs
            e_obs_v = e_obs
        shell_idx_v = assign_shells(s_mag_v, f_obs.shell_edges)
        shell_var = compute_patterson_shell_variance(
            e_obs_v.to(torch.float64), shell_idx_v, P=P,
        )
        w = 1.0 / shell_var.sqrt()
        w = w * (P / w.sum().clamp(min=1e-30))
        weights = w.to(f_obs.f_plm.real.dtype)

    xi = compute_ball_cross_correlation_coefficients(f_obs, f_calc, weights=weights)
    C, alphas, betas, gammas = evaluate_rotation_function_grid(
        xi, L, n_alpha=2 * L, n_beta=2 * L, n_gamma=2 * L,
    )
    peaks = find_rotation_peaks(
        C, alphas, betas, gammas,
        n_peaks=n_peaks, sigma_threshold=sigma_threshold,
    )
    if refine_subvoxel and len(peaks) > 0:
        head = peaks[:n_refine]
        head = refine_peaks_subvoxel(head, C, alphas, betas, gammas)
        peaks = head + peaks[n_refine:]
        peaks.sort(key=lambda r: r.score, reverse=True)
    return C, alphas, betas, gammas, peaks


# =============================================================================
# Convenience: Euler ↔ matrix using the Edmonds ZYZ convention
# =============================================================================


def rotation_matrix_from_edmonds_euler_batch(
    alpha: torch.Tensor, beta: torch.Tensor, gamma: torch.Tensor,
) -> torch.Tensor:
    """
    Vectorised Edmonds ZYZ Euler → R: R = R_z(α) R_y(β) R_z(γ).

    `alpha`, `beta`, `gamma`: identically-shaped real tensors. Returns
    `(..., 3, 3)` in the same dtype/device as the inputs. Equivalent to
    calling `rotation_matrix_from_edmonds_euler` per Euler triple, but
    avoids 9 small-tensor allocations per call.
    """
    ca, sa = torch.cos(alpha), torch.sin(alpha)
    cb, sb = torch.cos(beta), torch.sin(beta)
    cg, sg = torch.cos(gamma), torch.sin(gamma)
    zero = torch.zeros_like(alpha)
    one = torch.ones_like(alpha)
    Rz_a = torch.stack([
        torch.stack([ca, -sa, zero], dim=-1),
        torch.stack([sa,  ca, zero], dim=-1),
        torch.stack([zero, zero, one], dim=-1),
    ], dim=-2)
    Ry_b = torch.stack([
        torch.stack([cb,  zero, sb], dim=-1),
        torch.stack([zero, one, zero], dim=-1),
        torch.stack([-sb, zero, cb], dim=-1),
    ], dim=-2)
    Rz_c = torch.stack([
        torch.stack([cg, -sg, zero], dim=-1),
        torch.stack([sg,  cg, zero], dim=-1),
        torch.stack([zero, zero, one], dim=-1),
    ], dim=-2)
    return Rz_a @ Ry_b @ Rz_c


def rotation_matrix_from_edmonds_euler(
    alpha: float, beta: float, gamma: float, dtype=torch.float64,
) -> torch.Tensor:
    """
    Build R = R_z(α) R_y(β) R_z(γ)   (Edmonds active ZYZ).

    Equivalent to passing `[γ, β, α]` to
    `torchref.alignment.transform.rotation_matrix_from_euler`.
    """
    ca, sa = math.cos(alpha), math.sin(alpha)
    cb, sb = math.cos(beta), math.sin(beta)
    cg, sg = math.cos(gamma), math.sin(gamma)
    Rz_a = torch.tensor([[ca, -sa, 0.0], [sa, ca, 0.0], [0.0, 0.0, 1.0]], dtype=dtype)
    Ry_b = torch.tensor([[cb, 0.0, sb], [0.0, 1.0, 0.0], [-sb, 0.0, cb]], dtype=dtype)
    Rz_c = torch.tensor([[cg, -sg, 0.0], [sg, cg, 0.0], [0.0, 0.0, 1.0]], dtype=dtype)
    return Rz_a @ Ry_b @ Rz_c


def edmonds_euler_from_rotation_matrix(R: torch.Tensor) -> Tuple[float, float, float]:
    """
    Recover (α, β, γ) such that R = R_z(α) R_y(β) R_z(γ).
    Returns angles in radians; α, γ ∈ [0, 2π), β ∈ [0, π].
    Singular when β = 0 or π (only α+γ is determined); we set γ=0 in those cases.
    """
    R = R.to(torch.float64)
    cos_beta = R[2, 2].clamp(-1.0, 1.0).item()
    beta = math.acos(cos_beta)
    sin_beta = math.sin(beta)
    if abs(sin_beta) < 1e-9:
        # Degenerate: only α+γ is determined. Set γ=0.
        alpha = math.atan2(R[1, 0].item(), R[0, 0].item())
        gamma = 0.0
    else:
        alpha = math.atan2(R[1, 2].item(), R[0, 2].item())
        gamma = math.atan2(R[2, 1].item(), -R[2, 0].item())
    alpha = alpha % (2.0 * math.pi)
    gamma = gamma % (2.0 * math.pi)
    return alpha, beta, gamma


def rotation_angular_distance_deg(R1: torch.Tensor, R2: torch.Tensor) -> float:
    """Geodesic distance on SO(3) in degrees: arccos((tr(R1 R2^T) - 1)/2)."""
    R = R1.to(torch.float64) @ R2.to(torch.float64).T
    tr = (R[0, 0] + R[1, 1] + R[2, 2]).clamp(-1.0, 3.0).item()
    cos_a = max(-1.0, min(1.0, (tr - 1.0) / 2.0))
    return math.degrees(math.acos(cos_a))
