# ==========================================================
# Figure 4 Pocket Panels: Binding pocket with DED maps
#
# Generates 3 panels:
#   Panel 21: WDFo map + dark (8QL2) + extrapolated (7YYZ)
#   Panel 22: WDFo map + dark (8QL2) + TorchRef refined
#   Panel 23: TorchRef refined + extrapolated (7YYZ), no map
#
# Color scheme (consistent with figure4_ligand.pml):
#   Dark (8QL2):        gray80
#   Extrapolated (7YYZ): wheat
#   TorchRef refined:    marine
#
# Run from the paper/ directory:
#   cd paper
#   pymol figure4_difference_refinement/pymol_scripts/figure4_pocket.pml
#
# Requires CCP4 maps generated by:
#   cd figure4_difference_refinement/validation && bash run_validation.sh
# ==========================================================

reinitialize
viewport 800, 600
bg_color white
set ray_opaque_background, on
set depth_cue, 1
set ray_trace_mode, 1

# Visual settings
set cartoon_sidechain_helper, 1
set mesh_quality, 15
set mesh_grid_max, 1500
set mesh_width, 0.3
set surface_quality, 15
set stick_radius, 0.15

# 1. LOAD MODELS
load figure4_difference_refinement/data/8QL2.pdb, dark
load figure4_difference_refinement/data/7YYZ.pdb, extrapol
load figure4_difference_refinement/data/torchref_0p18.pdb, torchref
remove elem H

# 2. MAP LOADING & DOUBLE-DOUBLE EXPANSION
load figure4_difference_refinement/validation/output/torchref_IBL/validate_WDFo.ccp4, map_fo
map_double map_fo,
map_double map_fo,

# 3. IDENTIFY UNION POCKET (all residues within 4.5A of IBL in any model)
python
resis = set()
cmd.iterate("(resn IBL and chain B) around 4.5", "resis.add(resi)")
resi_list = "+".join(sorted(list(resis)))
cmd.select("pocket_res", f"resi {resi_list} and polymer")
cmd.select("ligand", "resn IBL and chain B")
python end

select pocket_sc, pocket_res and not (name N,C,O)
create carve_target, pocket_res

# 4. DISPLAY
hide everything
show cartoon
show sticks, ligand
show sticks, pocket_sc

# 5. COLORING (unified across ligand + pocket scripts)
# Dark: gray80
color gray80, dark and elem C
util.cnc dark

# Extrapolated (7YYZ): wheat
color wheat, extrapol and elem C
util.cnc extrapol

# TorchRef: marine
color marine, torchref and elem C
util.cnc torchref

# Transparency
set cartoon_transparency, 0.3, dark
set cartoon_transparency, 0.3, extrapol
set stick_transparency, 0.2, dark
set stick_transparency, 0.2, extrapol
set stick_transparency, 0.7, ligand

# 6. MULTI-LEVEL DIFFERENCE MAP (Green/Red)
python
levels = [(3.0, 1.0), (4.0, 2.0), (5.0, 3.0)]
carve_dist = 2.0
pos_col = "tv_green"
neg_col = "tv_red"

for sigma, width in levels:
    p_name = f"mesh_fo_pos_{sigma}"
    n_name = f"mesh_fo_neg_{sigma}"

    cmd.isomesh(p_name, "map_fo",  sigma, "carve_target", carve=carve_dist)
    cmd.isomesh(n_name, "map_fo", -sigma, "carve_target", carve=carve_dist)

    cmd.color(pos_col, p_name)
    cmd.color(neg_col, n_name)
    cmd.set("mesh_width", width, p_name)
    cmd.set("mesh_width", width, n_name)
python end

# 7. ORGANIZATION
group Models, dark extrapol torchref
group Maps_Fo, mesh_fo_*

hide everything, carve_target

# 8. VIEW (pocket view)
set_view (\
    -0.814730644,    0.331998408,   -0.475370347,\
    -0.152427554,   -0.913648665,   -0.376847744,\
    -0.559433341,   -0.234568968,    0.794983208,\
     0.000254968,    0.000073881,  -38.551216125,\
     9.442328453,  -21.226753235,   18.875190735,\
    28.829362869,   48.246856689,  -20.000000000 )

# ==========================================================
# PANEL 21: WDFo + dark + extrapolated (7YYZ)
# ==========================================================
disable torchref
enable dark
enable extrapol
enable Maps_Fo

draw 2400, 1800
png figure4_difference_refinement/panels/figure4_panel_21.png

# ==========================================================
# PANEL 22: WDFo + dark + TorchRef refined
# ==========================================================
disable extrapol
enable torchref

draw 2400, 1800
png figure4_difference_refinement/panels/figure4_panel_22.png

# ==========================================================
# PANEL 23: TorchRef refined + extrapolated (7YYZ), no map
# ==========================================================
enable extrapol
disable dark
disable Maps_Fo

draw 2400, 1800
png figure4_difference_refinement/panels/figure4_panel_23.png

print("Script complete. 3 pocket panels saved (21, 22, 23).")

quit
