# ==========================================================
# Figure 4 Ligand Panels: IBL ball-and-stick with DED maps
#
# Generates 3 panels:
#   Panel 11: WDFo map + dark (8QL2) + extrapolated (7YYZ)
#   Panel 12: WDFo map + dark (8QL2) + TorchRef refined
#   Panel 13: TorchRef refined + extrapolated (7YYZ), no map
#
# Color scheme (consistent with figure4_pocket.pml):
#   Dark (8QL2):        gray80
#   Extrapolated (7YYZ): wheat
#   TorchRef refined:    marine
#
# Run from the paper/ directory:
#   cd paper
#   pymol figure4_difference_refinement/pymol_scripts/figure4_ligand.pml
#
# Requires CCP4 maps generated by:
#   cd figure4_difference_refinement/validation && bash run_validation.sh
# ==========================================================

reinitialize
bg_color white
set ray_opaque_background, on
set ray_trace_mode, 1
set depth_cue, 0

# Mesh/surface quality
set mesh_quality, 3
set mesh_grid_max, 200
set surface_quality, 3

# 1. LOAD STRUCTURES
load figure4_difference_refinement/data/8QL2_no_altloc.pdb, dark
load figure4_difference_refinement/data/7YYZ.pdb, extrapol
load figure4_difference_refinement/data/torchref_0p18.pdb, torchref
remove elem H

# 2. LOAD WDFo MAP (from torchref validation)
load figure4_difference_refinement/validation/output/torchref_IBL/validate_WDFo.ccp4, wdfo_map
map_double wdfo_map,
map_double wdfo_map,

# 2b. MOVE MODELS INTO UNIT CELL so they overlap with the map
python
import numpy as np
from math import cos, sin, radians

def frac_matrix(sym):
    """Return Cartesian->fractional and fractional->Cartesian matrices from cell params."""
    a, b, c, al, be, ga = sym[0:6]
    al, be, ga = radians(al), radians(be), radians(ga)
    v = a * b * c * np.sqrt(1 - cos(al)**2 - cos(be)**2 - cos(ga)**2 + 2*cos(al)*cos(be)*cos(ga))
    cart2frac = np.array([
        [1/a, -cos(ga)/(a*sin(ga)), (cos(al)*cos(ga)-cos(be))/(a*sin(ga)*v/(b*c))],
        [0,   1/(b*sin(ga)),         (cos(be)*cos(ga)-cos(al))/(b*sin(ga)*v/(a*c))],
        [0,   0,                      a*b*sin(ga)/v]
    ])
    frac2cart = np.linalg.inv(cart2frac)
    return cart2frac, frac2cart

for obj in ["dark", "extrapol", "torchref"]:
    sym = cmd.get_symmetry(obj)
    if not sym:
        continue
    cart2frac, frac2cart = frac_matrix(sym)
    com = np.array(cmd.centerofmass(obj))
    com_frac = cart2frac @ com
    shift_frac = -np.floor(com_frac)
    shift_cart = frac2cart @ shift_frac
    cmd.translate(shift_cart.tolist(), obj)
python end

# 3. SELECTIONS
# Note: 7YYZ has IBL at resi 502, dark/torchref at resi 501
select IBL_dark, dark and resn IBL and chain B and resi 501 and not elem H
select IBL_extrapol, extrapol and resn IBL and not elem H
select IBL_torchref, torchref and resn IBL and not elem H
create IBL_combined, IBL_dark or IBL_extrapol or IBL_torchref

# 4. HIDE EVERYTHING
hide everything, all

# 5. BALL-AND-STICK DISPLAY
python
for sel in ["IBL_dark", "IBL_extrapol", "IBL_torchref"]:
    cmd.show("sticks", sel)
    cmd.show("spheres", sel)
    cmd.set("sphere_scale", 0.17, sel)
    cmd.set("stick_radius", 0.13, sel)
    cmd.set("stick_transparency", 0.2, sel)
    cmd.set("sphere_transparency", 0.2, sel)
python end

# 6. COLORING (unified across ligand + pocket scripts)
# Dark: gray80
color gray80, IBL_dark and elem C
color blue, IBL_dark and elem N
color red, IBL_dark and elem O

# Extrapolated (7YYZ): wheat
color wheat, IBL_extrapol and elem C
color blue, IBL_extrapol and elem N
color red, IBL_extrapol and elem O

# TorchRef: marine
color marine, IBL_torchref and elem C
color blue, IBL_torchref and elem N
color red, IBL_torchref and elem O

# 7. VOLUME RAMP DIFFERENCE MAP (Green/Red)
# Define ramp first, then create volume with carve
cmd.volume_ramp_new('ded_ramp', [\
     -5.0, 0.6, 0.0, 0.0, 0.15, \
     -4.0, 0.8, 0.0, 0.0, 0.12, \
     -3.0, 1.0, 0.3, 0.3, 0.08, \
     -2.5, 1.0, 0.3, 0.3, 0.0, \
      2.5, 0.3, 1.0, 0.3, 0.0, \
      3.0, 0.3, 1.0, 0.3, 0.08, \
      4.0, 0.0, 0.8, 0.0, 0.12, \
      5.0, 0.0, 0.6, 0.0, 0.15, \
    ])

volume vol_wdfo, wdfo_map, ramp=ded_ramp, selection=IBL_combined, carve=1.5

# 8. ORGANIZATION
group Models, dark extrapol torchref
group Maps, vol_wdfo

hide dark extrapol torchref

# 9. VIEW (IBL close-up)
python
com = cmd.centerofmass("IBL_combined")
cmd.set_view([
     0.107359871,   -0.979589105,   -0.169923216,
     0.614946246,    0.199726403,   -0.762849510,
     0.781220913,   -0.022595137,    0.623840988,
     0.000000000,    0.000000000,  -29.184953690,
     com[0],         com[1],         com[2],
    23.470010757,   34.864784241,  -20.000000000
])
python end

# ==========================================================
# PANEL 11: WDFo + dark + extrapolated (7YYZ)
# Z-order: dark (back) -> extrapol (front) -> volume (top)
# ==========================================================
hide everything
show sticks, IBL_dark
show spheres, IBL_dark
show sticks, IBL_extrapol
show spheres, IBL_extrapol
show volume, vol_wdfo

draw 2400, 1800
png figure4_difference_refinement/panels/figure4_panel_11.png

# ==========================================================
# PANEL 12: WDFo + dark + TorchRef refined
# Z-order: dark (back) -> volume -> torchref (front)
# ==========================================================
hide everything
show sticks, IBL_dark
show spheres, IBL_dark
show volume, vol_wdfo
show sticks, IBL_torchref
show spheres, IBL_torchref

draw 2400, 1800
png figure4_difference_refinement/panels/figure4_panel_12.png

# ==========================================================
# PANEL 13: extrapolated (back) + TorchRef refined (front), no map
# ==========================================================
hide everything
show sticks, IBL_extrapol
show spheres, IBL_extrapol
show sticks, IBL_torchref
show spheres, IBL_torchref

draw 2400, 1800
png figure4_difference_refinement/panels/figure4_panel_13.png

print("Script complete. 3 ligand panels saved (11, 12, 13).")

quit
