# ==========================================================
# Figure 4 Ligand Panels: IBL ball-and-stick with DED maps
#
# Generates 3 panels:
#   Panel 11: WDFo map + dark (8QL2) + extrapolated (7YYZ)
#   Panel 12: WDFo map + dark (8QL2) + TorchRef refined
#   Panel 13: TorchRef refined + extrapolated (7YYZ), no map
#
# Color scheme (consistent with figure4_pocket.pml):
#   Dark (8QL2):        gray80
#   Extrapolated (7YYZ): wheat
#   TorchRef refined:    marine
#
# Run from the paper/ directory:
#   cd paper
#   pymol figure4_difference_refinement/pymol_scripts/figure4_ligand.pml
#
# Requires CCP4 maps generated by:
#   cd figure4_difference_refinement/validation && bash run_validation.sh
# ==========================================================

reinitialize
bg_color white
set ray_opaque_background, on
set ray_trace_mode, 1
set depth_cue, 0

# Mesh/surface quality
set mesh_quality, 15
set mesh_grid_max, 1500
set surface_quality, 15

# 1. LOAD STRUCTURES
load figure4_difference_refinement/data/8QL2.pdb, dark
load figure4_difference_refinement/data/7YYZ.pdb, extrapol
load figure4_difference_refinement/data/torchref_0p18.pdb, torchref
remove elem H

# 2. LOAD WDFo MAP (from torchref validation)
load figure4_difference_refinement/validation/output/torchref_IBL/validate_WDFo.ccp4, wdfo_map
map_double wdfo_map,
map_double wdfo_map,

# 3. SELECTIONS
# Note: 7YYZ has IBL at resi 502, dark/torchref at resi 501
select IBL_dark, dark and resn IBL and chain B and resi 501 and not elem H
select IBL_extrapol, extrapol and resn IBL and chain B and resi 502 and not elem H
select IBL_torchref, torchref and resn IBL and chain B and resi 501 and not elem H
create IBL_combined, IBL_dark or IBL_extrapol or IBL_torchref

# 4. HIDE EVERYTHING
hide everything, all

# 5. BALL-AND-STICK DISPLAY
python
for sel in ["IBL_dark", "IBL_extrapol", "IBL_torchref"]:
    cmd.show("sticks", sel)
    cmd.show("spheres", sel)
    cmd.set("sphere_scale", 0.17, sel)
    cmd.set("stick_radius", 0.13, sel)
    cmd.set("stick_transparency", 0.2, sel)
    cmd.set("sphere_transparency", 0.2, sel)
python end

# 6. COLORING (unified across ligand + pocket scripts)
# Dark: gray80
color gray80, IBL_dark and elem C
color blue, IBL_dark and elem N
color red, IBL_dark and elem O

# Extrapolated (7YYZ): wheat
color wheat, IBL_extrapol and elem C
color blue, IBL_extrapol and elem N
color red, IBL_extrapol and elem O

# TorchRef: marine
color marine, IBL_torchref and elem C
color blue, IBL_torchref and elem N
color red, IBL_torchref and elem O

# 7. MULTI-LEVEL DIFFERENCE MAP (Green/Red)
set mesh_type, 1

python
mesh_levels = [(3.0, 0.3), (4.0, 1.0), (5.0, 2.5)]
carve = 1.5

for sigma, width in mesh_levels:
    neg_name = f"mesh_neg_{sigma}"
    pos_name = f"mesh_pos_{sigma}"
    cmd.isomesh(neg_name, "wdfo_map", -sigma, "IBL_combined", carve=carve)
    cmd.isomesh(pos_name, "wdfo_map",  sigma, "IBL_combined", carve=carve)
    cmd.color("tv_red", neg_name)
    cmd.color("tv_green", pos_name)
    cmd.set("mesh_width", width, neg_name)
    cmd.set("mesh_width", width, pos_name)
python end

# 8. ORGANIZATION
group Models, dark extrapol torchref
group Maps, mesh_neg_* mesh_pos_*

hide everything, IBL_combined

# 9. VIEW (IBL close-up)
set_view (\
     0.107359871,   -0.979589105,   -0.169923216,\
     0.614946246,    0.199726403,   -0.762849510,\
     0.781220913,   -0.022595137,    0.623840988,\
     0.000018273,    0.000030073,  -29.184953690,\
    13.772394180,  -17.207910538,   17.486206055,\
    23.470010757,   34.864784241,  -20.000000000 )

# ==========================================================
# PANEL 11: WDFo + dark + extrapolated (7YYZ)
# ==========================================================
disable torchref
enable dark
enable extrapol
enable Maps

draw 2400, 1800
png figure4_difference_refinement/panels/figure4_panel_11.png

# ==========================================================
# PANEL 12: WDFo + dark + TorchRef refined
# ==========================================================
disable extrapol
enable torchref

draw 2400, 1800
png figure4_difference_refinement/panels/figure4_panel_12.png

# ==========================================================
# PANEL 13: TorchRef refined + extrapolated (7YYZ), no map
# ==========================================================
enable extrapol
disable dark
disable Maps

draw 2400, 1800
png figure4_difference_refinement/panels/figure4_panel_13.png

print("Script complete. 3 ligand panels saved (11, 12, 13).")

quit
