#!/usr/bin/env python
"""Summarize median figure values from the metrics CSVs into a markdown file.

Pulls the headline medians behind main Figure 2 and Extended Figures 1-4 straight
from the aggregated CSVs (so the numbers in the text always match the plots) and
writes paper/FIGURE_MEDIANS.md.

Usage:
    ./.dev/bin/python paper/figure2_alphafold_start/analysis/summarize_medians.py
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd

BASE = Path(__file__).resolve().parent.parent          # figure2_alphafold_start/
PAPER = BASE.parent                                     # paper/
M = BASE / "runs" / "metrics"
EXF2_CSV = PAPER / "extended_figures" / "exF2" / "data" / "exF2_rfactor_by_resolution.csv"
EXF4_CSV = PAPER / "extended_figures" / "exF4" / "data" / "exF4_singlecore.csv"
FCALC_DIR = PAPER / "figure3_performance" / "data" / "fcalc"
OUT = PAPER / "FIGURE_MEDIANS.md"

TR = "torchref"                # canonical TorchRef arm
ENGINE_LABEL = {"prediction": "AlphaFold (start)", "refmac": "Refmac",
                "phenix": "PHENIX", "torchref": "TorchRef", TR: "TorchRef"}


def med(s):
    s = pd.to_numeric(s, errors="coerce").dropna()
    return (float(s.median()), len(s)) if len(s) else (float("nan"), 0)


def main():
    out = ["# Figure median values",
           "",
           "Auto-generated by `analysis/summarize_medians.py` from the metrics CSVs; "
           "numbers match the plotted figures. TorchRef = canonical arm "
           "`torchref` (xray 1 / geometry 0.2 / adp 0.02).",
           ""]

    # ── Main Fig 2A: R-factors, PHENIX-validated (fig_crossscore, scorer=phenix) ──
    # Restricted to the conserved set (identical structures across engines) so the
    # medians are comparable; see aggregate_figure_metrics.py.
    cs = pd.read_csv(M / "fig_crossscore.csv")
    php = cs[cs.scorer == "phenix"]
    conserved_file = M / "conserved_codes.txt"
    conserved = set(conserved_file.read_text().split()) if conserved_file.exists() else None
    if conserved:
        php = php[php.code.isin(conserved)]
    n_note = f" (conserved set, n={len(conserved)})" if conserved else ""
    out += [f"## Figure 2A — R-factors (PHENIX-validated){n_note}", "",
            "| Model | median R-work | median R-free | n |",
            "|---|---|---|---|"]
    for eng in ["prediction", "refmac", "phenix", TR]:
        sub = php[php.model_engine == eng]
        rw, n = med(sub.r_work)
        rf, _ = med(sub.r_free)
        out.append(f"| {ENGINE_LABEL[eng]} | {rw:.4f} | {rf:.4f} | {n} |")
    out.append("")

    # ── Main Fig 2B: geometry RMSZ (fig_geometry; RMSZ = rms/sigma) ──
    # Restricted to the conserved set so every engine is scored on identical
    # structures (matches plot_figure_af.py, which filters all panels to it).
    geo = pd.read_csv(M / "fig_geometry.csv")
    if conserved:
        geo = geo[geo.code.isin(conserved)]
    pairs = [("Bond", "rmsBOND", "sigBOND"), ("Angle", "rmsANGL", "sigANGL"),
             ("Chiral", "rmsCHIRAL", "sigCHIRAL"),
             ("MC B-factor", "rmsB_mc_bond", "sigB_mc_bond")]
    out += [f"## Figure 2B — geometry RMSZ (median; ideal = 1.0){n_note}", "",
            "| Model | " + " | ".join(f"{p[0]} RMSZ" for p in pairs) + " | n |",
            "|---|" + "---|" * (len(pairs) + 1)]
    for eng in ["refmac", "phenix", "torchref"]:
        sub = geo[geo.engine == eng]
        if sub.empty:
            continue
        cells, n_any = [], 0
        for _, rms, sig in pairs:
            with np.errstate(divide="ignore", invalid="ignore"):
                z = pd.to_numeric(sub[rms], errors="coerce") / pd.to_numeric(sub[sig], errors="coerce")
            v, n = med(z.replace([np.inf, -np.inf], np.nan))
            cells.append(f"{v:.2f}")
            n_any = max(n_any, n)
        out.append(f"| {ENGINE_LABEL[eng]} | " + " | ".join(cells) + f" | {n_any} |")
    out.append("")

    # ── Main Fig 2C: runtime (fig_runtime, wall_s -> min) ──
    # Conserved set (identical structures per engine), as in panels 2A/2B.
    rt = pd.read_csv(M / "fig_runtime.csv")
    if conserved:
        rt = rt[rt.code.isin(conserved)]
    out += [f"## Figure 2C — wall-clock runtime{n_note}", "",
            "| Engine | median runtime (min) | n |", "|---|---|---|"]
    med_min = {}
    for eng in ["refmac", "torchref", "phenix"]:
        sub = rt[rt.engine == eng]
        s, n = med(sub.wall_s)
        med_min[eng] = s / 60.0
        out.append(f"| {ENGINE_LABEL[eng]} | {s/60.0:.2f} | {n} |")
    if all(e in med_min for e in ("torchref", "refmac", "phenix")):
        out += ["",
                f"TorchRef vs Refmac: {med_min['torchref']/med_min['refmac']:.1f}× "
                f"({'slower' if med_min['torchref']>med_min['refmac'] else 'faster'}); "
                f"TorchRef vs PHENIX: {med_min['phenix']/med_min['torchref']:.1f}× faster."]
    out.append("")

    # ── Fig 2 run accounting: success counts + grouped failure reasons ──
    # Every engine attempted the same candidate set of placed AF models. "Validated"
    # = produced a PHENIX-scored R-factor; the headline medians use the conserved
    # intersection (all four engines validated). fig_failures.csv (from
    # aggregate_figure_metrics.py) classifies each non-validated structure as a
    # 'refine' failure (engine produced no model) or a 'score' failure (model OK but
    # the uniform PHENIX validator could not score it).
    rfac = pd.read_csv(M / "fig_rfactors.csv")
    fails = pd.read_csv(M / "fig_failures.csv") if (M / "fig_failures.csv").exists() \
        else pd.DataFrame(columns=["engine", "code", "category", "reason"])
    eng_order = ["prediction", "refmac", "phenix", "torchref"]
    succ = {e: int((rfac.engine == e).sum()) for e in eng_order}
    nfail = {e: int((fails.engine == e).sum()) for e in eng_order}
    cand = {e: succ[e] + nfail[e] for e in eng_order}
    N = max(cand.values()) if cand else 0
    out += [f"## Figure 2 — run accounting (N={N} candidates; conserved set "
            f"n={len(conserved) if conserved else 0})", "",
            "Each engine refined the same set of Phaser-placed AlphaFold models. "
            "*Validated* = produced a PHENIX-scored R-factor; the headline medians "
            "use the conserved intersection where all four engines validated.", "",
            "| Engine | validated | failed | candidates |", "|---|---|---|---|"]
    for e in eng_order:
        out.append(f"| {ENGINE_LABEL[e]} | {succ[e]} | {nfail[e]} | {cand[e]} |")
    out.append("")
    out += ["### Failure reasons (grouped)", ""]
    cat_label = {"refine": "refine", "score": "scoring", "other": "other"}
    for e in eng_order:
        sub = fails[fails.engine == e]
        if sub.empty:
            continue
        out.append(f"- **{ENGINE_LABEL[e]}** — {len(sub)} failed")
        grp = (sub.groupby(["category", "reason"]).size()
               .sort_values(ascending=False))
        for (cat, reason), n in grp.items():
            out.append(f"  - {n} × {cat_label.get(cat, cat)}: {reason}")
    out += ["",
            "Most failures trace to a **special-position pathology** in some placed "
            "AF models: it breaks the uniform PHENIX scorer (so the structure is "
            "unscoreable for *every* engine) and makes phenix.refine itself abort, "
            "while REFMAC and TorchRef refine it without error. TorchRef's only "
            "engine-side failures are OOMs at the 8 GB job limit (large structures; "
            "would pass at 16 GB); REFMAC had zero refinement failures.", ""]

    # ── Figure 3: F_calc GPU kernel speedup over cctbx (forward pass only) ──
    # cctbx has no autodiff, so only the forward structure-factor calc is
    # comparable. Speedup = cctbx CPU mean / TorchRef GPU mean, using the fastest
    # cctbx mean observed per structure (thread-invariant; the conservative choice).
    summ = sorted(FCALC_DIR.glob("results_*/summary.csv"))
    if summ:
        f3 = pd.read_csv(summ[-1])
        gpu, cpu = f3[f3.device == "gpu"], f3[f3.device == "cpu"]
        speed = []
        for _, g in gpu.iterrows():
            c = cpu[cpu.structure == g.structure]
            cctbx = c.cctbx_mean.min() if not c.empty else float("nan")
            if np.isfinite(cctbx) and np.isfinite(g.torchref_mean) and g.torchref_mean > 0:
                speed.append((g.structure, cctbx / g.torchref_mean))
        if speed:
            speed.sort(key=lambda t: t[1])
            gpu_name = "GPU"
            gj = sorted(summ[-1].parent.glob("*_gpu.json"))
            if gj:
                gpu_name = json.loads(gj[0].read_text()).get("gpu_name", "GPU")
            (lo_s, lo), (hi_s, hi) = speed[0], speed[-1]
            mid = float(np.median([s for _, s in speed]))
            out += ["## Figure 3 — F_calc GPU kernel speedup over cctbx", "",
                    f"Forward structure-factor calculation, TorchRef GPU ({gpu_name}) "
                    f"vs cctbx on CPU, over {len(speed)} structures. Speedup = cctbx "
                    f"time / TorchRef GPU time (fastest cctbx observed per structure). "
                    f"cctbx has no autodiff, so only the forward pass is compared.", "",
                    "| | speedup | structure |", "|---|---|---|",
                    f"| minimum | {lo:.0f}× | {lo_s} |",
                    f"| maximum | {hi:.0f}× | {hi_s} |",
                    f"| median | {mid:.0f}× | — |", ""]

    # ── ExF2: R-factor gap vs resolution (PHENIX-scored) ──
    e2 = pd.read_csv(EXF2_CSV)
    out += ["## Extended Figure 2 — R-factor gap (TorchRef − reference, PHENIX-scored)", "",
            f"n = {len(e2)} structures, resolution {e2.d_min.min():.2f}–{e2.d_min.max():.2f} Å.",
            "",
            "| Reference | median ΔR-work (pp) | median ΔR-free (pp) |",
            "|---|---|---|"]
    for ref in ["phenix", "refmac"]:
        dw, _ = med(e2[f"delta_rwork_{ref}"])
        df_, _ = med(e2[f"delta_rfree_{ref}"])
        out.append(f"| {ref.upper()} | {dw:+.2f} | {df_:+.2f} |")
    out.append("")

    # ── ExF3: cross-score matrix (model x scorer median R-free, paired) ──
    scorers = ["refmac", "phenix", "torchref"]
    out += ["## Extended Figure 3 — scorer-consistency matrix (median R-free)", "",
            "| Model | by REFMAC | by PHENIX | by TorchRef | n(paired) |",
            "|---|---|---|---|---|"]
    for eng in ["refmac", "phenix", TR, "prediction"]:
        sub = cs[cs.model_engine == eng]
        wide = sub.pivot_table(index="code", columns="scorer", values="r_free")
        avail = [s for s in scorers if s in wide.columns]
        paired = wide.dropna(subset=avail)
        cells = []
        for s in scorers:
            cells.append(f"{paired[s].median():.4f}" if s in paired else "—")
        out.append(f"| {ENGINE_LABEL[eng]} | " + " | ".join(cells) + f" | {len(paired)} |")
    out.append("")

    # ── ExF1: weight landscape — locked-default cell (geom 0.2, adp 0.02) ──
    wg = pd.read_csv(M / "weight_grid.csv")
    gsel = wg.geometry.unique()[np.argmin(np.abs(np.log(wg.geometry.unique()) - np.log(0.2)))]
    asel = wg.adp.unique()[np.argmin(np.abs(np.log(wg.adp.unique()) - np.log(0.02)))]
    cell = wg[(wg.geometry == gsel) & (wg.adp == asel)]
    out += ["## Extended Figure 1 — weight landscape, locked-default cell",
            "",
            f"Cell geometry={gsel:.3g}, adp={asel:.3g} (n={len(cell)} structures). "
            "NB: the weight screen runs on a fixed ~50-structure subset, so these "
            "medians are NOT comparable to the full-benchmark numbers above (different, "
            "smaller structure set).",
            "",
            "| metric | median |", "|---|---|"]
    for col, lab in [("bond_rmsz", "Bond RMSZ"), ("angle_rmsz", "Angle RMSZ"),
                     ("mc_b_rmsz", "MC B-factor RMSZ"), ("r_work", "R-work"),
                     ("r_free", "R-free")]:
        v, _ = med(cell[col])
        out.append(f"| {lab} | {v:.4f} |")
    gapv, _ = med(pd.to_numeric(cell.r_free, errors="coerce")
                  - pd.to_numeric(cell.r_work, errors="coerce"))
    out.append(f"| R-free − R-work gap | {gapv:.4f} |")
    out.append("")

    # ── ExF4: single-core runtime (Figure 2c re-timed at 1 CPU core) ──
    if EXF4_CSV.exists():
        sc = pd.read_csv(EXF4_CSV)
        sc_order = ["refmac", "torchref", "phenix"]   # speed order
        sc_med = {e: pd.to_numeric(sc.loc[sc.program == e, "wall_s"],
                                   errors="coerce").median() for e in sc_order}
        n_sc = sc.code.nunique()
        out += [f"## Extended Figure 4 — single-core runtime (Fig 2c at 1 CPU core)",
                "",
                f"All three programs pinned to **1 CPU core** over the conserved "
                f"benchmark (n={n_sc}); cf. Fig 2C which runs at 4 cores.",
                "",
                "| Engine | median runtime (min) | median runtime (s) |",
                "|---|---|---|"]
        for e in sc_order:
            out.append(f"| {ENGINE_LABEL[e]} | {sc_med[e]/60:.2f} | {sc_med[e]:.1f} |")
        if all(sc_med.get(e) for e in sc_order):
            out += ["",
                    f"TorchRef vs Refmac: {sc_med['torchref']/sc_med['refmac']:.1f}× "
                    f"slower; TorchRef vs PHENIX: "
                    f"{sc_med['phenix']/sc_med['torchref']:.1f}× faster."]
        out.append("")

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
