#!/usr/bin/env python
"""Summarize median figure values from the metrics CSVs into a markdown file.

Pulls the headline medians behind main Figure 2 and Extended Figures 1-4 straight
from the aggregated CSVs (so the numbers in the text always match the plots) and
writes paper/FIGURE_MEDIANS.md.

Usage:
    ./.dev/bin/python paper/figure2_alphafold_start/analysis/summarize_medians.py
"""
import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import wilcoxon

BASE = Path(__file__).resolve().parent.parent          # figure2_alphafold_start/
PAPER = BASE.parent                                     # paper/
M = BASE / "runs" / "metrics"
EXF2_CSV = PAPER / "extended_figures" / "exF2" / "data" / "exF2_rfactor_by_resolution.csv"
EXF4_CSV = PAPER / "extended_figures" / "exF4" / "data" / "exF4_singlecore.csv"
FCALC_DIR = PAPER / "figure3_performance" / "data" / "fcalc"
OUT = PAPER / "FIGURE_MEDIANS.md"

TR = "torchref"                # canonical TorchRef arm
ENGINE_LABEL = {"prediction": "AlphaFold (start)", "refmac": "Refmac",
                "phenix": "PHENIX", "torchref": "TorchRef", TR: "TorchRef"}


def med(s):
    s = pd.to_numeric(s, errors="coerce").dropna()
    return (float(s.median()), len(s)) if len(s) else (float("nan"), 0)


def _ratio_phrase(a_name, a, b_name, b):
    """'A vs B: N.Nx slower|faster', with the direction read off the numbers.

    Both runtime tables used to hardcode the word, which silently lies the moment a ranking
    changes -- and one did (PHENIX overtook TorchRef at 1 core on 2026-08-04).
    """
    if not a or not b or a != a or b != b:
        return f"{a_name} vs {b_name}: n/a"
    slower = a > b
    r = a / b if slower else b / a
    return f"{a_name} vs {b_name}: {r:.1f}× {'slower' if slower else 'faster'}"


def main(fcalc_dir=None):
    out = ["# Figure median values",
           "",
           "Auto-generated by `analysis/summarize_medians.py` from the metrics CSVs; "
           "numbers match the plotted figures. TorchRef = canonical arm "
           "`torchref` (xray 1 / geometry 0.2 / adp 0.02).",
           ""]

    # ── Main Fig 2A: R-factors, PHENIX-validated (fig_crossscore, scorer=phenix) ──
    # Restricted to the conserved set (identical structures across engines) so the
    # medians are comparable; see aggregate_figure_metrics.py.
    cs = pd.read_csv(M / "fig_crossscore.csv")
    php = cs[cs.scorer == "phenix"]
    conserved_file = M / "conserved_codes.txt"
    conserved = set(conserved_file.read_text().split()) if conserved_file.exists() else None
    if conserved:
        php = php[php.code.isin(conserved)]
    n_note = f" (conserved set, n={len(conserved)})" if conserved else ""
    out += [f"## Figure 2A — R-factors (PHENIX-validated){n_note}", "",
            "| Model | median R-work | median R-free | n |",
            "|---|---|---|---|"]
    for eng in ["prediction", "refmac", "phenix", TR]:
        sub = php[php.model_engine == eng]
        rw, n = med(sub.r_work)
        rf, _ = med(sub.r_free)
        out.append(f"| {ENGINE_LABEL[eng]} | {rw:.4f} | {rf:.4f} | {n} |")
    out.append("")

    # ── Main Fig 2A: PAIRED delta vs each reference ──
    # The headline comparison. Paired per structure, because difference-of-medians and
    # median-of-differences can disagree in SIGN on this benchmark -- both are tabulated so
    # the discrepancy is visible rather than a matter of which one someone happened to quote.
    out += [f"## Figure 2A — paired ΔR-free, TorchRef − reference{n_note}", "",
            "Median of the per-structure differences (negative = TorchRef better), with a "
            "10 000-sample bootstrap CI on that median and a Wilcoxon signed-rank p. "
            "`Δ of medians` is the difference of the two medians in the table above, shown "
            "for contrast: it is *not* the paired statistic and can differ in sign.", "",
            "| Reference | metric | n | median Δ (paired) | 95% CI | Wilcoxon p | "
            "TorchRef better / worse | Δ of medians |",
            "|---|---|---|---|---|---|---|---|"]
    wide = php.pivot_table(index="code", columns="model_engine",
                           values=["r_work", "r_free"])
    rng = np.random.default_rng(20260805)
    paired_rows = []
    for ref in ["refmac", "phenix"]:
        for metric, mlabel in [("r_free", "R-free"), ("r_work", "R-work")]:
            if (metric, TR) not in wide or (metric, ref) not in wide:
                continue
            pair = wide[[(metric, TR), (metric, ref)]].dropna()
            d = (pair[(metric, TR)] - pair[(metric, ref)]).values
            if not len(d):
                continue
            m = float(np.median(d))
            boot = np.median(rng.choice(d, size=(10000, d.size), replace=True), axis=1)
            lo, hi = np.percentile(boot, [2.5, 97.5])
            p = float(wilcoxon(pair[(metric, TR)], pair[(metric, ref)]).pvalue) \
                if np.any(d != 0) else 1.0
            dom = float(np.median(pair[(metric, TR)]) - np.median(pair[(metric, ref)]))
            out.append(f"| {ENGINE_LABEL[ref]} | {mlabel} | {len(d)} | {m:+.4f} | "
                       f"[{lo:+.4f}, {hi:+.4f}] | {p:.2e} | "
                       f"{int((d < 0).sum())} / {int((d > 0).sum())} | {dom:+.4f} |")
            paired_rows.append({"reference": ref, "metric": metric, "n": len(d),
                                "median_delta_paired": round(m, 6),
                                "ci95_low": round(float(lo), 6),
                                "ci95_high": round(float(hi), 6),
                                "wilcoxon_p": p,
                                "torchref_better": int((d < 0).sum()),
                                "torchref_worse": int((d > 0).sum()),
                                "delta_of_medians": round(dom, 6)})
    out.append("")

    # Same numbers as a source-data table, written from this one computation rather than
    # recomputed next to the figure.
    if paired_rows:
        sd = PAPER / "source_data"
        sd.mkdir(parents=True, exist_ok=True)
        pd.DataFrame(paired_rows).to_csv(sd / "figure2_panelA_paired_delta.csv", index=False)
        print(f"wrote {sd / 'figure2_panelA_paired_delta.csv'}")

    # ── Main Fig 2B: geometry RMSZ (fig_geometry; RMSZ = rms/sigma) ──
    # Restricted to the conserved set so every engine is scored on identical
    # structures (matches plot_figure_af.py, which filters all panels to it).
    geo = pd.read_csv(M / "fig_geometry.csv")
    if conserved:
        geo = geo[geo.code.isin(conserved)]
    pairs = [("Bond", "rmsBOND", "sigBOND"), ("Angle", "rmsANGL", "sigANGL"),
             ("Chiral", "rmsCHIRAL", "sigCHIRAL"),
             ("MC B-factor", "rmsB_mc_bond", "sigB_mc_bond")]
    out += [f"## Figure 2B — geometry RMSZ (median; ideal = 1.0){n_note}", "",
            "| Model | " + " | ".join(f"{p[0]} RMSZ" for p in pairs) + " | n |",
            "|---|" + "---|" * (len(pairs) + 1)]
    for eng in ["refmac", "phenix", "torchref"]:
        sub = geo[geo.engine == eng]
        if sub.empty:
            continue
        cells, n_any = [], 0
        for _, rms, sig in pairs:
            with np.errstate(divide="ignore", invalid="ignore"):
                z = pd.to_numeric(sub[rms], errors="coerce") / pd.to_numeric(sub[sig], errors="coerce")
            v, n = med(z.replace([np.inf, -np.inf], np.nan))
            cells.append(f"{v:.2f}")
            n_any = max(n_any, n)
        out.append(f"| {ENGINE_LABEL[eng]} | " + " | ".join(cells) + f" | {n_any} |")
    out.append("")

    # ── Main Fig 2C: runtime (fig_runtime, wall_s -> min) ──
    # Conserved set (identical structures per engine), as in panels 2A/2B.
    rt = pd.read_csv(M / "fig_runtime.csv")
    if conserved:
        rt = rt[rt.code.isin(conserved)]
    out += [f"## Figure 2C — wall-clock runtime{n_note}", "",
            "| Engine | median runtime (min) | n |", "|---|---|---|"]
    med_min = {}
    for eng in ["refmac", "torchref", "phenix"]:
        sub = rt[rt.engine == eng]
        s, n = med(sub.wall_s)
        med_min[eng] = s / 60.0
        out.append(f"| {ENGINE_LABEL[eng]} | {s/60.0:.2f} | {n} |")
    if all(e in med_min for e in ("torchref", "refmac", "phenix")):
        out += ["", "; ".join(_ratio_phrase("TorchRef", med_min["torchref"],
                                            ENGINE_LABEL[e], med_min[e])
                              for e in ("refmac", "phenix")) + "."]
    out.append("")

    # ── Fig 2 run accounting: success counts + grouped failure reasons ──
    # Every engine attempted the same candidate set of placed AF models. "Validated"
    # = produced a PHENIX-scored R-factor; the headline medians use the conserved
    # intersection (all four engines validated). fig_failures.csv (from
    # aggregate_figure_metrics.py) classifies each non-validated structure as a
    # 'refine' failure (engine produced no model) or a 'score' failure (model OK but
    # the uniform PHENIX validator could not score it).
    rfac = pd.read_csv(M / "fig_rfactors.csv")
    fails = pd.read_csv(M / "fig_failures.csv") if (M / "fig_failures.csv").exists() \
        else pd.DataFrame(columns=["engine", "code", "category", "reason"])
    eng_order = ["prediction", "refmac", "phenix", "torchref"]
    succ = {e: int((rfac.engine == e).sum()) for e in eng_order}
    nfail = {e: int((fails.engine == e).sum()) for e in eng_order}
    cand = {e: succ[e] + nfail[e] for e in eng_order}
    N = max(cand.values()) if cand else 0
    out += [f"## Figure 2 — run accounting (N={N} candidates; conserved set "
            f"n={len(conserved) if conserved else 0})", "",
            "Each engine refined the same set of Phaser-placed AlphaFold models. "
            "*Validated* = produced a PHENIX-scored R-factor; the headline medians "
            "use the conserved intersection where all four engines validated.", "",
            "| Engine | validated | failed | candidates |", "|---|---|---|---|"]
    for e in eng_order:
        out.append(f"| {ENGINE_LABEL[e]} | {succ[e]} | {nfail[e]} | {cand[e]} |")
    out.append("")
    out += ["### Failure reasons (grouped)", ""]
    cat_label = {"refine": "refine", "score": "scoring", "other": "other"}
    for e in eng_order:
        sub = fails[fails.engine == e]
        if sub.empty:
            continue
        out.append(f"- **{ENGINE_LABEL[e]}** — {len(sub)} failed")
        grp = (sub.groupby(["category", "reason"]).size()
               .sort_values(ascending=False))
        for (cat, reason), n in grp.items():
            out.append(f"  - {n} × {cat_label.get(cat, cat)}: {reason}")
    out += ["",
            "Most failures trace to a **special-position pathology** in some placed "
            "AF models: it breaks the uniform PHENIX scorer (so the structure is "
            "unscoreable for *every* engine) and makes phenix.refine itself abort, "
            "while REFMAC and TorchRef refine it without error. TorchRef's only "
            "engine-side failures are OOMs at the 8 GB job limit (large structures; "
            "would pass at 16 GB); REFMAC had zero refinement failures.", ""]

    # ── Figure 3: F_calc GPU kernel speedup over cctbx (forward pass only) ──
    # cctbx has no autodiff, so only the forward structure-factor calc is comparable.
    #
    # Uses the *min* (best-of-10) times, because that is what Figure 3a plots -- this section
    # previously used the means and reported 119x for a panel showing 125x. A summary that
    # quotes a different statistic than its own figure is worse than either choice alone.
    # Which run feeds this is an explicit argument, not the newest directory: the CPU model
    # the reference cctbx ran on moves this number by ~2x (121x on a generation-matched Xeon
    # 6230R vs 59x on a 2024 EPYC 9335), so letting it follow directory mtime would let the
    # headline speedup change without anyone choosing it.
    summ = ([Path(fcalc_dir) / "summary.csv"] if fcalc_dir
            else sorted(FCALC_DIR.glob("results_*/summary.csv")))
    if summ and summ[-1].exists():
        f3 = pd.read_csv(summ[-1])
        cpu_model = (summ[-1].parent / "cpu_model.txt")
        cpu_model = cpu_model.read_text().strip() if cpu_model.exists() else "unrecorded"
        gpu, cpu = f3[f3.device == "gpu"], f3[f3.device == "cpu"]
        speed = []
        for _, g in gpu.iterrows():
            c = cpu[cpu.structure == g.structure]
            cctbx = c.cctbx_min.min() if not c.empty else float("nan")
            if np.isfinite(cctbx) and np.isfinite(g.torchref_min) and g.torchref_min > 0:
                speed.append((g.structure, cctbx / g.torchref_min))
        if speed:
            speed.sort(key=lambda t: t[1])
            gpu_name = "GPU"
            gj = sorted(summ[-1].parent.glob("*_gpu.json"))
            if gj:
                gpu_name = json.loads(gj[0].read_text()).get("gpu_name", "GPU")
            (lo_s, lo), (hi_s, hi) = speed[0], speed[-1]
            mid = float(np.median([s for _, s in speed]))
            out += ["## Figure 3 — F_calc GPU kernel speedup over cctbx", "",
                    f"Forward structure-factor calculation, TorchRef GPU ({gpu_name}) "
                    f"vs cctbx on **{cpu_model}**, over {len(speed)} structures. "
                    f"Speedup = cctbx time / TorchRef GPU time, both best-of-10 (fastest "
                    f"cctbx observed per structure), matching what the panel plots. cctbx "
                    f"has no autodiff, so only the forward pass is compared. This covers "
                    f"all {len(speed)} structures; the panel omits 5BOV as a triclinic "
                    f"outlier, so its on-figure median is slightly higher.", "",
                    f"The reference CPU is stated because it sets this number: "
                    f"`cpu_xeon6230R` (Cascade Lake, Q1 2020) is contemporaneous with the "
                    f"A100 (mid-2020); a 2024 `cpu_epyc9335` runs the same unchanged cctbx "
                    f"code 1.95x faster and halves the ratio (median 59x on that CPU, "
                    f"against the table below). The generation-matched pair is quoted.", "",
                    "| | speedup | structure |", "|---|---|---|",
                    f"| minimum | {lo:.0f}× | {lo_s} |",
                    f"| maximum | {hi:.0f}× | {hi_s} |",
                    f"| median | {mid:.0f}× | — |", ""]

    # ── ExF2: R-factor gap vs resolution (PHENIX-scored) ──
    e2 = pd.read_csv(EXF2_CSV)
    out += ["## Extended Figure 2 — R-factor gap (TorchRef − reference, PHENIX-scored)", "",
            f"n = {len(e2)} structures, resolution {e2.d_min.min():.2f}–{e2.d_min.max():.2f} Å.",
            "",
            "| Reference | median ΔR-work (pp) | median ΔR-free (pp) |",
            "|---|---|---|"]
    for ref in ["phenix", "refmac"]:
        dw, _ = med(e2[f"delta_rwork_{ref}"])
        df_, _ = med(e2[f"delta_rfree_{ref}"])
        out.append(f"| {ref.upper()} | {dw:+.2f} | {df_:+.2f} |")
    out.append("")

    # ── ExF3: cross-score matrix (model x scorer median R-free, paired) ──
    scorers = ["refmac", "phenix", "torchref"]
    out += ["## Extended Figure 3 — scorer-consistency matrix (median R-free)", "",
            "| Model | by REFMAC | by PHENIX | by TorchRef | n(paired) |",
            "|---|---|---|---|---|"]
    for eng in ["refmac", "phenix", TR, "prediction"]:
        sub = cs[cs.model_engine == eng]
        wide = sub.pivot_table(index="code", columns="scorer", values="r_free")
        avail = [s for s in scorers if s in wide.columns]
        paired = wide.dropna(subset=avail)
        cells = []
        for s in scorers:
            cells.append(f"{paired[s].median():.4f}" if s in paired else "—")
        out.append(f"| {ENGINE_LABEL[eng]} | " + " | ".join(cells) + f" | {len(paired)} |")
    out.append("")

    # ── ExF1: weight landscape — locked-default cell (geom 0.2, adp 0.02) ──
    wg = pd.read_csv(M / "weight_grid.csv")
    gsel = wg.geometry.unique()[np.argmin(np.abs(np.log(wg.geometry.unique()) - np.log(0.2)))]
    asel = wg.adp.unique()[np.argmin(np.abs(np.log(wg.adp.unique()) - np.log(0.02)))]
    cell = wg[(wg.geometry == gsel) & (wg.adp == asel)]
    out += ["## Extended Figure 1 — weight landscape, locked-default cell",
            "",
            f"Cell geometry={gsel:.3g}, adp={asel:.3g} (n={len(cell)} structures). "
            "NB: the weight screen runs on a fixed ~50-structure subset, so these "
            "medians are NOT comparable to the full-benchmark numbers above (different, "
            "smaller structure set).",
            "",
            "| metric | median |", "|---|---|"]
    for col, lab in [("bond_rmsz", "Bond RMSZ"), ("angle_rmsz", "Angle RMSZ"),
                     ("mc_b_rmsz", "MC B-factor RMSZ"), ("r_work", "R-work"),
                     ("r_free", "R-free")]:
        v, _ = med(cell[col])
        out.append(f"| {lab} | {v:.4f} |")
    gapv, _ = med(pd.to_numeric(cell.r_free, errors="coerce")
                  - pd.to_numeric(cell.r_work, errors="coerce"))
    out.append(f"| R-free − R-work gap | {gapv:.4f} |")
    out.append("")

    # ── ExF4: single-core runtime (Figure 2c re-timed at 1 CPU core) ──
    if EXF4_CSV.exists():
        sc = pd.read_csv(EXF4_CSV)
        # Speed order MEASURED, not the former literal ["refmac", "torchref", "phenix"]:
        # TorchRef and PHENIX swapped on the 2026-08-04 interleaved run, so a fixed order
        # silently mislabels the table (same fix as plot_singlecore.py / Fig 2c).
        sc_med = {e: pd.to_numeric(sc.loc[sc.program == e, "wall_s"],
                                   errors="coerce").median()
                  for e in ("refmac", "torchref", "phenix")}
        sc_order = sorted((e for e in sc_med if sc_med[e] == sc_med[e]),
                          key=lambda e: sc_med[e])
        n_sc = sc.code.nunique()
        out += [f"## Extended Figure 4 — single-core runtime (Fig 2c at 1 CPU core)",
                "",
                f"All three programs pinned to **1 CPU core** over the conserved "
                f"benchmark (n={n_sc}); cf. Fig 2C which runs at 4 cores.",
                "",
                "| Engine | median runtime (min) | median runtime (s) |",
                "|---|---|---|"]
        for e in sc_order:
            out.append(f"| {ENGINE_LABEL[e]} | {sc_med[e]/60:.2f} | {sc_med[e]:.1f} |")
        if all(sc_med.get(e) for e in sc_order):
            # Direction is derived, not asserted: this line used to hardcode "slower"/
            # "faster", and PHENIX overtook TorchRef at 1 core, which would have printed
            # "0.9x faster".
            out += ["", "; ".join(_ratio_phrase("TorchRef", sc_med["torchref"],
                                                ENGINE_LABEL[e], sc_med[e])
                                  for e in ("refmac", "phenix")) + "."]
        out.append("")

    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}")
    print("\n".join(out))


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--fcalc-dir", default=None,
                    help="Figure 3a results dir whose cctbx reference feeds the GPU-speedup "
                         "section. State it explicitly: the reference CPU model moves that "
                         "number ~2x. Default: newest under data/fcalc/.")
    main(**vars(ap.parse_args()))
