"""
Pure-PyTorch Patterson-based rotation search.

Replaces the old `ball_transform.py` (which depended on jax / s2fft / s2ball /
spherical / quaternionic). All math is implemented with `torchref.alignment.sh`
and `torchref.alignment.wigner` and runs on whatever device the inputs live on.

Conventions (locked, asserted by tests/unit/alignment/test_*.py and the
synthetic-rotation integration test):

  Forward analytical SH expansion:
        f_{p,l,m} = Σ_{i ∈ shell p} v_i · conj(Y_{l,m}(ŝ_i))
  with Friedel mates `(-s_i, v_i)` included so odd-l rows are zero by
  construction.

  Cross-correlation in Wigner-D basis:
        ξ_{l,m,n} = Σ_p w_p · f_{obs}[p,l,n] · conj(f_{calc}[p,l,m])
        C(R)      = Σ_{l,m,n} ξ_{l,m,n} · D^l_{m,n}(R)         (Edmonds D)

  Recovered rotation: the Euler triple (α, β, γ) at the maximum of C is the
  rotation R = R_z(α) R_y(β) R_z(γ) (Edmonds active ZYZ) such that
        s_calc = R · s_obs                                    (column vector)
  for the test scenario where F_calc was generated by applying R to the model
  coordinates. To build a (3, 3) matrix using
  `torchref.alignment.transform.rotation_matrix_from_euler` (which interprets
  its args as `R = R_z(γ_arg) R_y(β_arg) R_z(α_arg)`), pass `[γ, β, α]`.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import List, Optional, Tuple

import torch
import torch.nn.functional as F

from ..sh import (
    assign_shells,
    compute_patterson_shell_variance,
    equal_count_shell_edges,
    sh_expand_ball,
)
from ..wigner import (
    AdaptiveRotationFunction,
    evaluate_rotation_function_grid,
    evaluate_rotation_function_pointwise,
)


# =============================================================================
# Data containers
# =============================================================================


@dataclass
class BallHarmonicCoefficients:
    """Output of `compute_ball_harmonic_coefficients`."""

    f_plm: torch.Tensor  # complex, shape (P, L, 2L-1)
    L: int
    P: int
    shell_edges: torch.Tensor  # real, shape (P+1,)
    shell_centers: torch.Tensor  # real, shape (P,)
    shell_counts: torch.Tensor  # int64, shape (P,)


@dataclass
class RotationPeak:
    """A single peak of the rotation function."""

    alpha: float
    beta: float
    gamma: float
    score: float       # value of C at the peak (real part)
    sigma: float       # (C - mean) / std at the peak


# =============================================================================
# Forward expansion
# =============================================================================


def compute_ball_harmonic_coefficients(
    s_vectors: torch.Tensor,
    values: torch.Tensor,
    L: int = 48,
    P: int = 24,
    shell_edges: Optional[torch.Tensor] = None,
    d_min: Optional[float] = None,
    d_max: Optional[float] = None,
    enforce_friedel: bool = True,
    zsymm: int = 1,
    skip_odd_l: bool = False,
) -> BallHarmonicCoefficients:
    """
    Compute the ball-harmonic expansion of a real scattered-point field.

    Parameters
    ----------
    s_vectors : (N, 3) real tensor
        Reciprocal-lattice vectors in 1/Å.
    values : (N,) real tensor
        Sample values (e.g. |E(h)|) at each `s_vector`.
    L : int, default 48
        Angular bandlimit.
    P : int, default 24
        Number of radial shells.
    shell_edges : (P+1,) real tensor, optional
        Pre-computed shell boundaries (in |s|). If None, use equal-count
        binning between `d_min` and `d_max` (or full range).
    d_min, d_max : float, optional
        Resolution bounds (Å). When given, reflections outside [1/d_max, 1/d_min]
        in |s| are discarded.
    enforce_friedel : bool, default True
        Augment input with (-s, value) pairs and zero odd-l rows after expansion.

    Returns
    -------
    BallHarmonicCoefficients
    """
    s_mag = s_vectors.norm(dim=-1)
    if d_min is not None or d_max is not None:
        s_lo = 1.0 / d_max if d_max is not None else 0.0
        s_hi = 1.0 / d_min if d_min is not None else float("inf")
        keep = (s_mag >= s_lo) & (s_mag <= s_hi)
        s_vectors = s_vectors[keep]
        values = values[keep]
        s_mag = s_mag[keep]

    if shell_edges is None:
        shell_edges, _ = equal_count_shell_edges(s_mag, P)
    shell_centers = 0.5 * (shell_edges[:-1] + shell_edges[1:])
    shell_idx = assign_shells(s_mag, shell_edges)
    keep = shell_idx >= 0
    s_vectors = s_vectors[keep]
    values = values[keep]
    shell_idx = shell_idx[keep]

    shell_counts = torch.bincount(shell_idx, minlength=P).to(torch.int64)

    f_plm = sh_expand_ball(
        s_vectors, values, shell_idx, P, L,
        enforce_friedel=enforce_friedel,
        zsymm=zsymm, skip_odd_l=skip_odd_l,
    )

    return BallHarmonicCoefficients(
        f_plm=f_plm, L=L, P=P,
        shell_edges=shell_edges,
        shell_centers=shell_centers,
        shell_counts=shell_counts,
    )


# =============================================================================
# Cross-correlation
# =============================================================================


def compute_ball_cross_correlation_coefficients(
    f_obs: BallHarmonicCoefficients,
    f_calc: BallHarmonicCoefficients,
    weights: Optional[torch.Tensor] = None,
) -> torch.Tensor:
    """
    Wigner-D coefficients ξ_{l,m,n} of the rotation function (see module docstring).

    ξ_{l,m,n} = Σ_p w_p · f_{obs}[p, l, n] · conj(f_{calc}[p, l, m])
    """
    assert f_obs.L == f_calc.L, "bandwidths must match"
    assert f_obs.P == f_calc.P, "shell counts must match"
    P, L = f_obs.P, f_obs.L

    if weights is None:
        # Default: weight by shell count (equal weight per reflection).
        counts = f_obs.shell_counts.to(torch.float64)
        w_sum = counts.sum().clamp(min=1.0)
        weights = (counts / w_sum).to(f_obs.f_plm.dtype)
    else:
        weights = weights.to(f_obs.f_plm.dtype)

    xi = torch.einsum(
        "p,pln,plm->lmn",
        weights,
        f_obs.f_plm,
        torch.conj(f_calc.f_plm),
    )
    return xi


# =============================================================================
# Peak finding
# =============================================================================


def _circular_pad_gamma_alpha(x: torch.Tensor, r: int) -> torch.Tensor:
    """
    Wrap-pad axes 0 (γ) and -1 (α) by `r` voxels using circular boundary
    conditions, and constant-pad axis 1 (β) with -inf (non-periodic).
    Input shape (Γ, B, Α); output shape (Γ+2r, B+2r, Α+2r).
    """
    if r <= 0:
        return x
    x = torch.cat([x[-r:], x, x[:r]], dim=0)                    # wrap γ
    x = torch.cat([x[..., -r:], x, x[..., :r]], dim=-1)         # wrap α
    pad_shape = list(x.shape)
    pad_shape[1] = r
    neg_inf = torch.full(pad_shape, float("-inf"), dtype=x.dtype, device=x.device)
    x = torch.cat([neg_inf, x, neg_inf], dim=1)                 # β: -inf pad
    return x


def find_rotation_peaks(
    C: torch.Tensor,
    alphas: torch.Tensor,
    betas: torch.Tensor,
    gammas: torch.Tensor,
    n_peaks: int = 200,
    sigma_threshold: float = 0.0,
    cluster_radius_voxels: int = 2,
) -> List[RotationPeak]:
    """
    Extract local maxima of `C` and return them sorted by descending value.

    Periodic in α and γ (FFT axes); β is non-periodic but mirror at the
    endpoints isn't enforced — the user is expected to oversample β.

    Patterson centrosymmetry C(R) = C(-R) is left to the caller — when needed,
    add a post-processing step that merges peaks with R and -R representations.

    Vectorised over voxels: NMS is implemented as `C == max_pool3d(C)` with
    `kernel = 2·r + 1`, circular in α and γ. The legacy per-voxel Python loop
    with per-iteration `.item()` is replaced with a single sort + bulk
    `.tolist()` at the end — same semantics on randomly-real data (exact
    ties are vanishingly rare), but device-portable and ~1-2 orders of
    magnitude faster.
    """
    C_real = C.real
    n_gamma, n_beta, n_alpha = C_real.shape
    flat_stats = C_real.flatten()

    mean = flat_stats.mean()
    std = flat_stats.std().clamp(min=1e-30)
    threshold = mean + sigma_threshold * std

    r = int(cluster_radius_voxels)
    if r > 0:
        padded = _circular_pad_gamma_alpha(C_real, r)
        # max_pool3d wants (N, C, D, H, W). Add batch+channel dims, then strip.
        pooled = F.max_pool3d(
            padded.unsqueeze(0).unsqueeze(0),
            kernel_size=2 * r + 1, stride=1, padding=0,
        )[0, 0]
        is_local_max = C_real >= pooled
    else:
        is_local_max = torch.ones_like(C_real, dtype=torch.bool)

    above_threshold = C_real >= threshold
    candidate = is_local_max & above_threshold
    candidate_flat = candidate.flatten()
    cand_idx = candidate_flat.nonzero(as_tuple=False).flatten()
    if cand_idx.numel() == 0:
        return []
    cand_vals = C_real.flatten().index_select(0, cand_idx)

    # Sort descending; truncate to n_peaks.
    top_k = min(int(n_peaks), int(cand_vals.numel()))
    sort_vals, sort_perm = torch.sort(cand_vals, descending=True)
    sel_flat_idx = cand_idx.index_select(0, sort_perm[:top_k])
    sel_vals = sort_vals[:top_k]

    # Convert flat → (g, b, a). Periodic axes have already been deduped, so
    # plain integer arithmetic is sufficient.
    nba = n_beta * n_alpha
    ig = sel_flat_idx // nba
    rem = sel_flat_idx - ig * nba
    ib = rem // n_alpha
    ia = rem - ib * n_alpha

    sigmas = (sel_vals - mean) / std

    # Bulk transfer to Python lists, then build dataclasses.
    a_list = alphas.index_select(0, ia).tolist()
    b_list = betas.index_select(0, ib).tolist()
    g_list = gammas.index_select(0, ig).tolist()
    v_list = sel_vals.tolist()
    s_list = sigmas.tolist()
    return [
        RotationPeak(alpha=a, beta=b, gamma=g, score=v, sigma=s)
        for a, b, g, v, s in zip(a_list, b_list, g_list, v_list, s_list)
    ]


# =============================================================================
# Adaptive-grid peak finding
# =============================================================================


def _adaptive_global_stats(arf: AdaptiveRotationFunction) -> Tuple[float, float]:
    """
    Sample-weighted global mean and std across all β-slices.

    Every voxel of every slice contributes equally — the adaptive grid is
    already sample-uniform in SO(3) sense (each voxel covers a near-constant
    `sin(β)/(pmax(β)·qmax(β))` solid angle), so simple mean/std is correct.
    """
    flat = torch.cat([s.real.reshape(-1) for s in arf.slices])
    mean = float(flat.mean().item())
    std = float(flat.std().clamp(min=1e-30).item())
    return mean, std


def _slice_nms_mask(slice_C: torch.Tensor, r_alpha: int, r_gamma: int) -> torch.Tensor:
    """
    2-D non-maximum-suppression for one β-slice, circular in both α and γ.

    `slice_C` is real-valued (γ, α). Returns a boolean mask of local maxima.
    """
    if r_alpha <= 0 and r_gamma <= 0:
        return torch.ones_like(slice_C, dtype=torch.bool)
    n_gamma, n_alpha = slice_C.shape
    r_a = max(r_alpha, 0)
    r_g = max(r_gamma, 0)
    # Clamp radii so we never wrap past the slice's own period — at β = 0 the
    # γ axis has length 1, at β = π the α axis has length 1.
    r_a = min(r_a, max(n_alpha - 1, 0))
    r_g = min(r_g, max(n_gamma - 1, 0))
    if r_a == 0 and r_g == 0:
        return torch.ones_like(slice_C, dtype=torch.bool)
    # Circular pad in γ (axis 0) then α (axis 1).
    x = slice_C
    if r_g > 0:
        x = torch.cat([x[-r_g:], x, x[:r_g]], dim=0)
    if r_a > 0:
        x = torch.cat([x[:, -r_a:], x, x[:, :r_a]], dim=1)
    pooled = F.max_pool2d(
        x.unsqueeze(0).unsqueeze(0),
        kernel_size=(2 * r_g + 1, 2 * r_a + 1),
        stride=1, padding=0,
    )[0, 0]
    return slice_C >= pooled


def _sample_slice_at(
    slice_C: torch.Tensor,
    alpha_grid: torch.Tensor,
    gamma_grid: torch.Tensor,
    alpha_q: float,
    gamma_q: float,
) -> float:
    """
    Nearest-neighbour sample of a β-slice at a query (α, γ) in radians.
    """
    n_gamma, n_alpha = slice_C.shape
    two_pi = 2.0 * math.pi
    a0 = float(alpha_grid[0].item())
    g0 = float(gamma_grid[0].item())
    da = two_pi / n_alpha
    dg = two_pi / n_gamma
    ia = int(round((alpha_q - a0) / da)) % n_alpha
    ig = int(round((gamma_q - g0) / dg)) % n_gamma
    return float(slice_C[ig, ia].item())


def _so3_greedy_nms(
    alpha: torch.Tensor,
    beta: torch.Tensor,
    gamma: torch.Tensor,
    values: torch.Tensor,
    nms_radius_rad: float,
    keep_at_most: int,
) -> torch.Tensor:
    """
    Greedy SO(3) non-max suppression by angular distance between rotations.

    Walks the candidates in descending `values` order; keeps a candidate iff
    its angular distance `arccos((tr(R_cand · R_kept^T) − 1) / 2)` exceeds
    `nms_radius_rad` from every already-kept rotation. Returns the indices
    of the kept candidates in the order they were accepted (i.e. by
    descending score).

    Complexity: `O(N · K)` matrix-trace ops where `K = min(keep_at_most, N)`
    — the inner loop runs entirely in PyTorch on the host device.
    """
    n = alpha.shape[0]
    if n == 0:
        return torch.zeros(0, dtype=torch.long, device=alpha.device)
    R_all = rotation_matrix_from_edmonds_euler_batch(alpha, beta, gamma)  # (n, 3, 3)
    order = torch.argsort(values, descending=True)

    cos_thresh = math.cos(nms_radius_rad)
    kept_indices: List[int] = []
    kept_R = R_all.new_zeros((0, 3, 3))

    for i in order.tolist():
        Ri = R_all[i]                                                # (3, 3)
        if kept_R.shape[0] > 0:
            # tr(Ri · R_kept^T) over the batch of kept rotations.
            tr = torch.einsum("ab,kab->k", Ri, kept_R)
            # angular distance = arccos((tr − 1) / 2). Compare against
            # cosine to avoid the acos call entirely.
            cos_theta = ((tr - 1.0) * 0.5).clamp(-1.0, 1.0)
            if (cos_theta > cos_thresh).any().item():
                continue
        kept_indices.append(i)
        kept_R = torch.cat([kept_R, Ri.unsqueeze(0)], dim=0)
        if len(kept_indices) >= keep_at_most:
            break

    return torch.tensor(kept_indices, dtype=torch.long, device=alpha.device)


def find_rotation_peaks_adaptive(
    arf: AdaptiveRotationFunction,
    n_peaks: int = 200,
    sigma_threshold: float = 0.0,
    cluster_radius_deg: float = 6.0,
    nms_radius_deg: float = 6.0,
    candidate_cap: int = 10000,
) -> List[RotationPeak]:
    """
    Local-maximum peak finder for the ragged adaptive Euler grid.

    Algorithm:
        1. Per-slice 2-D NMS (circular in α and γ, radius converted from
           `cluster_radius_deg` to a per-slice voxel count).
        2. Threshold + truncate to the top `candidate_cap` survivors across
           all slices (bounds the cost of the next step).
        3. Greedy SO(3) non-max suppression: walk candidates in descending
           score; keep iff angular distance to every already-kept rotation
           is > `nms_radius_deg`. This subsumes the role the dense path's
           `max_pool3d` played and is geometry-aware — duplicate "polar"
           peaks differing only in α+γ (β≈0) or α−γ (β≈π) have angular
           distance ≈ 0 and are correctly collapsed.
        4. Truncate to top `n_peaks` and attach Z-score using the
           globally-pooled mean / std.
    """
    n_beta = arf.betas.shape[0]
    mean, std = _adaptive_global_stats(arf)
    threshold = mean + sigma_threshold * std

    # Per-slice local maxima + threshold. Collect onto torch tensors directly
    # to avoid per-candidate .item() round-trips.
    alpha_chunks: List[torch.Tensor] = []
    beta_chunks: List[torch.Tensor] = []
    gamma_chunks: List[torch.Tensor] = []
    value_chunks: List[torch.Tensor] = []
    for k in range(n_beta):
        slice_C = arf.slices[k].real
        n_gamma_k, n_alpha_k = slice_C.shape
        r_a = max(1, int(round(cluster_radius_deg * n_alpha_k / 360.0)))
        r_g = max(1, int(round(cluster_radius_deg * n_gamma_k / 360.0)))

        is_max = _slice_nms_mask(slice_C, r_alpha=r_a, r_gamma=r_g)
        is_max = is_max & (slice_C >= threshold)
        if not bool(is_max.any().item()):
            continue
        ig_idx, ia_idx = torch.nonzero(is_max, as_tuple=True)
        vals = slice_C[ig_idx, ia_idx]
        a_grid_k = arf.alpha_grids[k]
        g_grid_k = arf.gamma_grids[k]
        alpha_chunks.append(a_grid_k.index_select(0, ia_idx))
        gamma_chunks.append(g_grid_k.index_select(0, ig_idx))
        beta_chunks.append(arf.betas[k].expand_as(vals))
        value_chunks.append(vals)

    if not value_chunks:
        return []

    alpha_all = torch.cat(alpha_chunks)
    beta_all = torch.cat(beta_chunks)
    gamma_all = torch.cat(gamma_chunks)
    value_all = torch.cat(value_chunks)

    # Cap the candidate set by raw score before the O(N·K) SO(3) NMS.
    if value_all.shape[0] > candidate_cap:
        top_v, top_i = torch.topk(value_all, candidate_cap)
        alpha_all = alpha_all.index_select(0, top_i)
        beta_all = beta_all.index_select(0, top_i)
        gamma_all = gamma_all.index_select(0, top_i)
        value_all = top_v

    # Greedy SO(3) NMS.
    keep_idx = _so3_greedy_nms(
        alpha_all, beta_all, gamma_all, value_all,
        nms_radius_rad=math.radians(nms_radius_deg),
        keep_at_most=int(n_peaks),
    )

    if keep_idx.numel() == 0:
        return []

    alpha_keep = alpha_all.index_select(0, keep_idx).tolist()
    beta_keep = beta_all.index_select(0, keep_idx).tolist()
    gamma_keep = gamma_all.index_select(0, keep_idx).tolist()
    value_keep = value_all.index_select(0, keep_idx).tolist()

    return [
        RotationPeak(
            alpha=a, beta=b, gamma=g, score=v,
            sigma=(v - mean) / max(std, 1e-30),
        )
        for (a, b, g, v) in zip(alpha_keep, beta_keep, gamma_keep, value_keep)
    ]


def refine_peaks_subvoxel_adaptive(
    peaks: List[RotationPeak],
    arf: AdaptiveRotationFunction,
) -> List[RotationPeak]:
    """
    Sub-voxel parabolic refinement for adaptive-grid peaks.

    For each peak at (α, β_k, γ):
        * α and γ refinement uses the per-slice spacing `2π / pmax_k`,
          `2π / qmax_k`. Skipped at slices where the relevant axis has
          length 1 (β ≈ 0 → no γ refinement; β ≈ π → no α refinement).
        * β refinement fits a parabola through the values at the same
          (α, γ) sampled into slices k-1 and k+1 by nearest-neighbour.
          Boundary slices use db = 0.
    """
    if not peaks:
        return list(peaks)

    n_beta = arf.betas.shape[0]
    beta_grid = arf.betas
    # Beta is uniform in our construction, so a single dβ is correct.
    if n_beta > 1:
        dbeta = float((beta_grid[1] - beta_grid[0]).item())
    else:
        dbeta = 0.0

    out: List[RotationPeak] = []
    for p in peaks:
        # Locate the host β-slice.
        ib = int(round((p.beta - float(beta_grid[0].item())) / dbeta)) if dbeta > 0 else 0
        ib = max(0, min(ib, n_beta - 1))
        slice_C = arf.slices[ib].real
        a_grid = arf.alpha_grids[ib]
        g_grid = arf.gamma_grids[ib]
        n_gamma_k, n_alpha_k = slice_C.shape
        da = 2.0 * math.pi / n_alpha_k
        dg = 2.0 * math.pi / n_gamma_k

        # Integer voxel indices.
        a0 = float(a_grid[0].item())
        g0 = float(g_grid[0].item())
        ia = int(round((p.alpha - a0) / da)) % n_alpha_k
        ig = int(round((p.gamma - g0) / dg)) % n_gamma_k

        y0 = float(slice_C[ig, ia].item())

        # α refinement.
        if n_alpha_k >= 3:
            am = (ia - 1) % n_alpha_k
            ap = (ia + 1) % n_alpha_k
            yam = float(slice_C[ig, am].item())
            yap = float(slice_C[ig, ap].item())
            denom = yam - 2.0 * y0 + yap
            if abs(denom) > 1e-30:
                d_a = max(-1.0, min(1.0, 0.5 * (yam - yap) / denom))
            else:
                d_a = 0.0
            alpha_new = (p.alpha + d_a * da) % (2.0 * math.pi)
        else:
            alpha_new = p.alpha

        # γ refinement.
        if n_gamma_k >= 3:
            gm = (ig - 1) % n_gamma_k
            gp = (ig + 1) % n_gamma_k
            ygm = float(slice_C[gm, ia].item())
            ygp = float(slice_C[gp, ia].item())
            denom = ygm - 2.0 * y0 + ygp
            if abs(denom) > 1e-30:
                d_g = max(-1.0, min(1.0, 0.5 * (ygm - ygp) / denom))
            else:
                d_g = 0.0
            gamma_new = (p.gamma + d_g * dg) % (2.0 * math.pi)
        else:
            gamma_new = p.gamma

        # β refinement: sample neighbouring slices at (α, γ).
        if 0 < ib < n_beta - 1 and dbeta > 0:
            v_prev = _sample_slice_at(
                arf.slices[ib - 1].real, arf.alpha_grids[ib - 1],
                arf.gamma_grids[ib - 1], p.alpha, p.gamma,
            )
            v_next = _sample_slice_at(
                arf.slices[ib + 1].real, arf.alpha_grids[ib + 1],
                arf.gamma_grids[ib + 1], p.alpha, p.gamma,
            )
            denom = v_prev - 2.0 * y0 + v_next
            if abs(denom) > 1e-30:
                d_b = max(-1.0, min(1.0, 0.5 * (v_prev - v_next) / denom))
            else:
                d_b = 0.0
            beta_new = max(0.0, min(math.pi, p.beta + d_b * dbeta))
        else:
            beta_new = p.beta

        out.append(RotationPeak(
            alpha=alpha_new, beta=beta_new, gamma=gamma_new,
            score=p.score, sigma=p.sigma,
        ))
    return out


# =============================================================================
# Sub-voxel refinement (pointwise gradient ascent on C(R) using autograd)
# =============================================================================


def _parabolic_offset_vec(
    y_minus: torch.Tensor, y_zero: torch.Tensor, y_plus: torch.Tensor,
) -> torch.Tensor:
    """
    Vectorised sub-voxel offset for a quadratic through three samples
    y(-1), y(0), y(+1). Returns δ clamped to [-1, 1]; degenerate cells
    (|denom| < 1e-30) get δ = 0.
    """
    denom = y_minus - 2.0 * y_zero + y_plus
    bad = denom.abs() < 1e-30
    safe_denom = torch.where(bad, torch.ones_like(denom), denom)
    delta = 0.5 * (y_minus - y_plus) / safe_denom
    delta = torch.where(bad, torch.zeros_like(delta), delta)
    return delta.clamp(-1.0, 1.0)


def refine_peaks_subvoxel(
    peaks: List[RotationPeak],
    C: torch.Tensor,
    alphas: torch.Tensor,
    betas: torch.Tensor,
    gammas: torch.Tensor,
) -> List[RotationPeak]:
    """
    Sub-voxel refinement of integer-grid peaks by separable quadratic fitting.

    For each peak, fits y = a + b·δ + c·δ² through the values at ±1 voxel along
    each of α, β, γ axes (α and γ periodic with the grid length, β not).
    Returns refined peaks with interpolated angles and values.

    Vectorised over all peaks: indices and neighbour samples are gathered in
    a single batched op; the legacy per-peak `.item()` loop is replaced with
    one `.tolist()` at the end (cuts ~12·K scalar GPU↔CPU round-trips).
    """
    if not peaks:
        return list(peaks)

    n_gamma, n_beta, n_alpha = C.shape
    Cr = C.real
    device = Cr.device
    real_dtype = alphas.dtype

    dalpha = (alphas[1] - alphas[0]).item()
    dgamma = (gammas[1] - gammas[0]).item()
    dbeta = (betas[1] - betas[0]).item() if betas.numel() > 1 else 0.0
    a0 = alphas[0].item()
    g0 = gammas[0].item()
    b0 = betas[0].item()

    # Pack peak coordinates into tensors in one go.
    K = len(peaks)
    alpha_in = torch.tensor([p.alpha for p in peaks], dtype=real_dtype, device=device)
    beta_in = torch.tensor([p.beta for p in peaks], dtype=real_dtype, device=device)
    gamma_in = torch.tensor([p.gamma for p in peaks], dtype=real_dtype, device=device)

    # Integer voxel indices.
    ia = ((alpha_in - a0) / dalpha).round().long() % n_alpha
    ig = ((gamma_in - g0) / dgamma).round().long() % n_gamma
    if dbeta > 0:
        ib = ((beta_in - b0) / dbeta).round().long().clamp(0, n_beta - 1)
    else:
        ib = torch.zeros(K, dtype=torch.long, device=device)

    am = (ia - 1) % n_alpha
    ap = (ia + 1) % n_alpha
    gm = (ig - 1) % n_gamma
    gp = (ig + 1) % n_gamma
    # β neighbours: clamp at boundaries; we zero δβ explicitly there below.
    ibm = (ib - 1).clamp(min=0, max=n_beta - 1)
    ibp = (ib + 1).clamp(min=0, max=n_beta - 1)

    y0 = Cr[ig, ib, ia]
    ya_m = Cr[ig, ib, am]
    ya_p = Cr[ig, ib, ap]
    yg_m = Cr[gm, ib, ia]
    yg_p = Cr[gp, ib, ia]
    yb_m = Cr[ig, ibm, ia]
    yb_p = Cr[ig, ibp, ia]

    da = _parabolic_offset_vec(ya_m, y0, ya_p)
    dg = _parabolic_offset_vec(yg_m, y0, yg_p)
    db = _parabolic_offset_vec(yb_m, y0, yb_p)
    # Zero out β offset at the boundary (single-sided / undefined).
    at_b_boundary = (ib == 0) | (ib == n_beta - 1)
    db = torch.where(at_b_boundary, torch.zeros_like(db), db)
    if dbeta <= 0:
        db = torch.zeros_like(db)

    two_pi = 2.0 * math.pi
    alpha_new = (alphas.index_select(0, ia) + da * dalpha) % two_pi
    gamma_new = (gammas.index_select(0, ig) + dg * dgamma) % two_pi
    beta_new = (betas.index_select(0, ib) + db * dbeta).clamp(min=0.0, max=math.pi)

    a_list = alpha_new.tolist()
    b_list = beta_new.tolist()
    g_list = gamma_new.tolist()
    return [
        RotationPeak(
            alpha=a, beta=b, gamma=g, score=p.score, sigma=p.sigma,
        )
        for a, b, g, p in zip(a_list, b_list, g_list, peaks)
    ]


# =============================================================================
# Top-level entry
# =============================================================================


def ball_rotation_search(
    s_obs: torch.Tensor,
    e_obs: torch.Tensor,
    s_calc: torch.Tensor,
    e_calc: torch.Tensor,
    L: int = 48,
    P: int = 24,
    n_peaks: int = 200,
    d_min: Optional[float] = None,
    d_max: Optional[float] = None,
    refine_subvoxel: bool = True,
    n_refine: int = 20,
    sigma_threshold: float = 1.0,
    weights: Optional[torch.Tensor] = None,
    auto_variance_weights: bool = True,
    zsymm: int = 1,
    skip_odd_l: bool = False,
) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, List[RotationPeak]]:
    """
    End-to-end Patterson rotation search.

    Parameters
    ----------
    s_obs, s_calc : (N, 3) real
        Reciprocal-lattice vectors. Need not be the same set of HKLs for obs
        and calc — but should sample the same resolution range.
    e_obs, e_calc : (N,) real
        Normalized structure-factor amplitudes (E-values). Pass |F|² instead
        if you want a strict Patterson rotation function.
    L, P : int, default 48 / 24
        Bandlimit and shell count.
    d_min, d_max : float
        Resolution limits in Å (s_min = 1/d_max, s_max = 1/d_min).
    n_peaks : int, default 200
        Number of rotation peaks to return.
    refine_subvoxel : bool, default True
        If True, refine the top `n_refine` peaks by gradient ascent on the
        pointwise rotation function (autograd, no FFT).
    n_refine : int
        Number of peaks to refine.
    sigma_threshold : float
        Minimum (peak - mean)/std for a peak to be kept.
    weights : (P,) real, optional
        Per-shell weights in the cross-correlation. Default: shell-count weighted,
        or (when `auto_variance_weights=True`) inverse-sqrt of the empirical
        per-shell variance of the obs Patterson coefficient.
    auto_variance_weights : bool, default True
        Compute `weights = 1/√Var(e_obs)_p` per shell when no explicit `weights`
        are supplied. This is the LERF1-style empirical variance correction —
        downweights shells whose observed Patterson coefficient is dominated by
        intermolecular contributions (high-symmetry crystals).

    Returns
    -------
    C : complex tensor (n_gamma, n_beta, n_alpha)
        Rotation function on Euler grid (Edmonds order).
    alphas, betas, gammas : real 1-D tensors
        Grid coordinates.
    peaks : list of RotationPeak (sorted by descending score)
    """
    # NOTE: `zsymm` is applied only to the OBSERVED side. The observed
    # Patterson is spacegroup-invariant by physics, so SH coefficients with
    # m not divisible by ZSYMM are noise. The calc Patterson comes from a
    # rotated P1 ensemble that is NOT spacegroup-invariant — those m's
    # carry real signal and must be kept. Phaser does the same asymmetric
    # filtering (DataMR.cc applies the m-filter; Ensemble.cc does not).
    f_obs = compute_ball_harmonic_coefficients(
        s_obs, e_obs, L=L, P=P, d_min=d_min, d_max=d_max,
        zsymm=zsymm, skip_odd_l=skip_odd_l,
    )
    # Share shell edges between obs and calc — required for the cross-correlation
    # to be meaningful (same radial binning on both sides).
    f_calc = compute_ball_harmonic_coefficients(
        s_calc, e_calc, L=L, P=P, shell_edges=f_obs.shell_edges,
        zsymm=1, skip_odd_l=skip_odd_l,
    )

    if auto_variance_weights and weights is None:
        s_mag_obs = s_obs.norm(dim=-1)
        if d_min is not None or d_max is not None:
            s_lo = 1.0 / d_max if d_max is not None else 0.0
            s_hi = 1.0 / d_min if d_min is not None else float("inf")
            keep_obs = (s_mag_obs >= s_lo) & (s_mag_obs <= s_hi)
            s_mag_v = s_mag_obs[keep_obs]
            e_obs_v = e_obs[keep_obs]
        else:
            s_mag_v = s_mag_obs
            e_obs_v = e_obs
        shell_idx_v = assign_shells(s_mag_v, f_obs.shell_edges)
        shell_var = compute_patterson_shell_variance(
            e_obs_v.to(torch.float64), shell_idx_v, P=P,
        )
        w = 1.0 / shell_var.sqrt()
        w = w * (P / w.sum().clamp(min=1e-30))
        weights = w.to(f_obs.f_plm.real.dtype)

    xi = compute_ball_cross_correlation_coefficients(f_obs, f_calc, weights=weights)
    C, alphas, betas, gammas = evaluate_rotation_function_grid(
        xi, L, n_alpha=2 * L, n_beta=2 * L, n_gamma=2 * L,
    )
    peaks = find_rotation_peaks(
        C, alphas, betas, gammas,
        n_peaks=n_peaks, sigma_threshold=sigma_threshold,
    )
    if refine_subvoxel and len(peaks) > 0:
        head = peaks[:n_refine]
        head = refine_peaks_subvoxel(head, C, alphas, betas, gammas)
        peaks = head + peaks[n_refine:]
        peaks.sort(key=lambda r: r.score, reverse=True)
    return C, alphas, betas, gammas, peaks


# =============================================================================
# Convenience: Euler ↔ matrix using the Edmonds ZYZ convention
# =============================================================================


def rotation_matrix_from_edmonds_euler_batch(
    alpha: torch.Tensor, beta: torch.Tensor, gamma: torch.Tensor,
) -> torch.Tensor:
    """
    Vectorised Edmonds ZYZ Euler → R: R = R_z(α) R_y(β) R_z(γ).

    `alpha`, `beta`, `gamma`: identically-shaped real tensors. Returns
    `(..., 3, 3)` in the same dtype/device as the inputs. Equivalent to
    calling `rotation_matrix_from_edmonds_euler` per Euler triple, but
    avoids 9 small-tensor allocations per call.
    """
    ca, sa = torch.cos(alpha), torch.sin(alpha)
    cb, sb = torch.cos(beta), torch.sin(beta)
    cg, sg = torch.cos(gamma), torch.sin(gamma)
    zero = torch.zeros_like(alpha)
    one = torch.ones_like(alpha)
    Rz_a = torch.stack([
        torch.stack([ca, -sa, zero], dim=-1),
        torch.stack([sa,  ca, zero], dim=-1),
        torch.stack([zero, zero, one], dim=-1),
    ], dim=-2)
    Ry_b = torch.stack([
        torch.stack([cb,  zero, sb], dim=-1),
        torch.stack([zero, one, zero], dim=-1),
        torch.stack([-sb, zero, cb], dim=-1),
    ], dim=-2)
    Rz_c = torch.stack([
        torch.stack([cg, -sg, zero], dim=-1),
        torch.stack([sg,  cg, zero], dim=-1),
        torch.stack([zero, zero, one], dim=-1),
    ], dim=-2)
    return Rz_a @ Ry_b @ Rz_c


def rotation_matrix_from_edmonds_euler(
    alpha: float, beta: float, gamma: float, dtype=torch.float64,
) -> torch.Tensor:
    """
    Build R = R_z(α) R_y(β) R_z(γ)   (Edmonds active ZYZ).

    Equivalent to passing `[γ, β, α]` to
    `torchref.alignment.transform.rotation_matrix_from_euler`.
    """
    ca, sa = math.cos(alpha), math.sin(alpha)
    cb, sb = math.cos(beta), math.sin(beta)
    cg, sg = math.cos(gamma), math.sin(gamma)
    Rz_a = torch.tensor([[ca, -sa, 0.0], [sa, ca, 0.0], [0.0, 0.0, 1.0]], dtype=dtype)
    Ry_b = torch.tensor([[cb, 0.0, sb], [0.0, 1.0, 0.0], [-sb, 0.0, cb]], dtype=dtype)
    Rz_c = torch.tensor([[cg, -sg, 0.0], [sg, cg, 0.0], [0.0, 0.0, 1.0]], dtype=dtype)
    return Rz_a @ Ry_b @ Rz_c


def edmonds_euler_from_rotation_matrix(R: torch.Tensor) -> Tuple[float, float, float]:
    """
    Recover (α, β, γ) such that R = R_z(α) R_y(β) R_z(γ).
    Returns angles in radians; α, γ ∈ [0, 2π), β ∈ [0, π].
    Singular when β = 0 or π (only α+γ is determined); we set γ=0 in those cases.
    """
    R = R.to(torch.float64)
    cos_beta = R[2, 2].clamp(-1.0, 1.0).item()
    beta = math.acos(cos_beta)
    sin_beta = math.sin(beta)
    if abs(sin_beta) < 1e-9:
        # Degenerate: only α+γ is determined. Set γ=0.
        alpha = math.atan2(R[1, 0].item(), R[0, 0].item())
        gamma = 0.0
    else:
        alpha = math.atan2(R[1, 2].item(), R[0, 2].item())
        gamma = math.atan2(R[2, 1].item(), -R[2, 0].item())
    alpha = alpha % (2.0 * math.pi)
    gamma = gamma % (2.0 * math.pi)
    return alpha, beta, gamma


def rotation_angular_distance_deg(R1: torch.Tensor, R2: torch.Tensor) -> float:
    """Geodesic distance on SO(3) in degrees: arccos((tr(R1 R2^T) - 1)/2)."""
    R = R1.to(torch.float64) @ R2.to(torch.float64).T
    tr = (R[0, 0] + R[1, 1] + R[2, 2]).clamp(-1.0, 3.0).item()
    cos_a = max(-1.0, min(1.0, (tr - 1.0) / 2.0))
    return math.degrees(math.acos(cos_a))
